remote_theme: just-the-docs/just-the-docs
color_scheme: dark # options: 'light' or 'dark'

aux_links:
  "Visit RuleWorld on GitHub!":
    - "https://github.com/RuleWorld"

twitter_username: bionetgen
