remote_theme: just-the-docs/just-the-docs
color_scheme: dark # options: 'light' or 'dark'

search_enabled: true

aux_links:
  "Visit RuleWorld on GitHub!":
    - "https://github.com/RuleWorld"

twitter_username: bionetgen

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-229745903-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
