# Regression test: byte-identical reactions generated by two different
# reaction rules must be folded into a single network entry whose
# statistical factor accounts for both contributions.
#
# Fails if the .net reaction block contains more than one reaction line
# or if the folded entry does not carry the summed factor 2*k.

get_filename_component(model_name "${MODEL_PATH}" NAME_WE)
get_filename_component(output_dir "${OUTPUT_PATH}" DIRECTORY)

execute_process(
    COMMAND "${BNG_PERL_EXECUTABLE}" "${BNG2_PATH}" --outdir "${output_dir}" "${MODEL_PATH}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error
)

if(NOT result EQUAL 0)
    message(FATAL_ERROR "BNG2 cross-rule merge fixture failed with ${result}. Output:\n${output}${error}")
endif()

set(network_path "${output_dir}/${model_name}.net")
if(NOT EXISTS "${network_path}")
    message(FATAL_ERROR "Expected network output was not created: ${network_path}")
endif()

file(READ "${network_path}" network)

# Isolate the reaction block
string(REGEX MATCH "begin reactions(.*)end reactions" block_match "${network}")
if(block_match STREQUAL "")
    message(FATAL_ERROR "No reaction block found in ${network_path}:\n${network}")
endif()
set(reaction_block "${CMAKE_MATCH_1}")

# Every reaction line is tagged with its generating rule(s) (#_R...).
# There must be exactly one reaction line: the duplicate folded away.
string(REGEX MATCHALL "#_R[0-9,_]+" rule_refs "${reaction_block}")
list(LENGTH rule_refs n_rule_refs)
if(NOT n_rule_refs EQUAL 1)
    message(FATAL_ERROR "Expected 1 reaction entry after cross-rule merge, found ${n_rule_refs}:\n${reaction_block}")
endif()

# The merged entry must keep both rule references...
string(FIND "${reaction_block}" "#_R1,_R2" merge_idx)
if(merge_idx EQUAL -1)
    message(FATAL_ERROR "Merged reaction does not reference both rules (#_R1,_R2):\n${reaction_block}")
endif()

# ...and the summed statistical factor (k from each rule -> 2*k).
string(FIND "${reaction_block}" "2*k" factor_idx)
if(factor_idx EQUAL -1)
    message(FATAL_ERROR "Merged reaction is missing summed statistical factor 2*k:\n${reaction_block}")
endif()
