application: rbmrepo
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:                                                                      
- name: jinja2                                                                  
  version: latest    
  

handlers:

- url: /stylesheets
  static_dir: stylesheets
- url: /script
  static_dir: script
  
- url: /.*
  script: submitModel2.app
  

