par_list={
   1:{'name':"Nav",'value':"6.022e8",'unit':"",'type':"Avogadro number for 1 um^3"},
   2:{'name':"rxn_layer_t",'value':"0.01",'unit':"um",'type':""},
   3:{'name':"vol_EC",'value':"20.0",'unit':"um^3",'type':""},
   4:{'name':"sa_PM",'value':"0.4/rxn_layer_t",'unit':"um^2",'type':""},
   5:{'name':"vol_CP",'value':"4.0",'unit':"um^3",'type':""},
   6:{'name':"sa_NM",'value':"0.1/rxn_layer_t",'unit':"um^2",'type':""},
   7:{'name':"vol_NU",'value':"1.0",'unit':"um^3",'type':""},
   8:{'name':"sa_EM",'value':"0.05/rxn_layer_t",'unit':"um^2",'type':""},
   9:{'name':"vol_EN",'value':"0.5",'unit':"um^3",'type':""},
   10:{'name':"kp_LR",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   11:{'name':"km_LR",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   12:{'name':"kp_LL",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   13:{'name':"km_LL",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   14:{'name':"k_R_endo",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   15:{'name':"k_recycle",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   16:{'name':"k_R_transphos",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   17:{'name':"k_R_dephos",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   18:{'name':"kp_R_TF",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   19:{'name':"km_R_TF",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   20:{'name':"kp_R_TFp",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   21:{'name':"km_R_TFp",'value':"10.0",'unit':"/s",'type':"Unimolecular reaction"},
   22:{'name':"k_TF_transphos",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   23:{'name':"k_TF_dephos",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   24:{'name':"kp_TF_TF",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   25:{'name':"km_TF_TF",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   26:{'name':"kp_TF_p1",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   27:{'name':"km_TF_p1",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   28:{'name':"k_transcribe",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   29:{'name':"k_translate",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   30:{'name':"k_mRNA_to_CP",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   31:{'name':"k_mRNA_deg",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   32:{'name':"k_P_deg",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   33:{'name':"k_Im_bind_CP",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   34:{'name':"k_Im_unbind_CP",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   35:{'name':"k_Im_bind_NU",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   36:{'name':"k_Im_unbind_NU",'value':"10.0",'unit':"/s",'type':"Unimolecular reaction"},
   37:{'name':"k_Im_enters_NP",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   38:{'name':"k_Im_exits_NP",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   39:{'name':"k_Im_cross_NP",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   40:{'name':"kp_P1_p2",'value':"0.1*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   41:{'name':"km_P1_p2",'value':"1.0",'unit':"/s",'type':"Unimolecular reaction"},
   42:{'name':"L0",'value':"1000",'unit':"Number",'type':""},
   43:{'name':"R0",'value':"200",'unit':"Number",'type':""},
   44:{'name':"TF0",'value':"200",'unit':"Number",'type':""},
   45:{'name':"DNA0",'value':"2",'unit':"Number",'type':""},
   46:{'name':"Im0",'value':"40",'unit':"Number",'type':""},
   47:{'name':"NP0",'value':"4",'unit':"Number",'type':""},
   48:{'name':"T",'value':"298.25",'unit':"K",'type':""},
   49:{'name':"h",'value':"rxn_layer_t",'unit':"um",'type':""},
   50:{'name':"Rs",'value':"0.002564",'unit':"um",'type':""},
   51:{'name':"Rc",'value':"0.0015",'unit':"um",'type':""},
   52:{'name':"gamma",'value':"0.5722",'unit':"",'type':"Euler's constant"},
   53:{'name':"KB",'value':"1.3806488e-19",'unit':"cm^2.kg/K.s^2",'type':"Boltzmann constant"},
   54:{'name':"mu_EC",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   55:{'name':"mu_PM",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   56:{'name':"mu_CP",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   57:{'name':"mu_NM",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   58:{'name':"mu_NU",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   59:{'name':"mu_EM",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   60:{'name':"mu_EN",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"}}

mol_list={
   1:{'name':"s1",'type':"3D",'dif':"KB*T/(6*PI*mu_EC*Rs)"},
   2:{'name':"s2",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   3:{'name':"s3",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   4:{'name':"s4",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   5:{'name':"s5",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   6:{'name':"s6",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   7:{'name':"s7",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   8:{'name':"s8",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   9:{'name':"s9",'type':"3D",'dif':"KB*T/(6*PI*mu_EC*(2)^(1/3)*Rs)"},
   10:{'name':"s10",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   11:{'name':"s11",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   12:{'name':"s12",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   13:{'name':"s13",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   14:{'name':"s14",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   15:{'name':"s15",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   16:{'name':"s16",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   17:{'name':"s17",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   18:{'name':"s18",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   19:{'name':"s19",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   20:{'name':"s20",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   21:{'name':"s21",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   22:{'name':"s22",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   23:{'name':"s23",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   24:{'name':"s24",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   25:{'name':"s25",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   26:{'name':"s26",'type':"3D",'dif':"KB*T/(6*PI*mu_EN*(2)^(1/3)*Rs)"},
   27:{'name':"s27",'type':"3D",'dif':"KB*T/(6*PI*mu_EN*Rs)"},
   28:{'name':"s28",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   29:{'name':"s29",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   30:{'name':"s30",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   31:{'name':"s31",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   32:{'name':"s32",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   33:{'name':"s33",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   34:{'name':"s34",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   35:{'name':"s35",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   36:{'name':"s36",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   37:{'name':"s37",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   38:{'name':"s38",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   39:{'name':"s39",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   40:{'name':"s40",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   41:{'name':"s41",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   42:{'name':"s42",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   43:{'name':"s43",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   44:{'name':"s44",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   45:{'name':"s45",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   46:{'name':"s46",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   47:{'name':"s47",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   48:{'name':"s48",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   49:{'name':"s49",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   50:{'name':"s50",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   51:{'name':"s51",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   52:{'name':"s52",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   53:{'name':"s53",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   54:{'name':"s54",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   55:{'name':"s55",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   56:{'name':"s56",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   57:{'name':"s57",'type':"2D",'dif':"KB*T*LOG((mu_EM*h/(SQRT(2)*Rc*(mu_CP+mu_EN)/2))-gamma)/(4*PI*mu_EM*h)"},
   58:{'name':"s58",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*(2)^(1/3)*Rs)"},
   59:{'name':"s59",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*(3)^(1/3)*Rs)"},
   60:{'name':"s60",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   61:{'name':"s61",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   62:{'name':"s62",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(2)^(1/3)*Rs)"},
   63:{'name':"s63",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(3)^(1/3)*Rs)"},
   64:{'name':"s64",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   65:{'name':"s65",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(3)^(1/3)*Rs)"},
   66:{'name':"s66",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   67:{'name':"s67",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   68:{'name':"s68",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   69:{'name':"s69",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*(2)^(1/3)*Rs)"},
   70:{'name':"s70",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   71:{'name':"s71",'type':"2D",'dif':"KB*T*LOG((mu_NM*h/(Rc*(mu_CP+mu_NU)/2))-gamma)/(4*PI*mu_NM*h)"},
   72:{'name':"s72",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   73:{'name':"s73",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(2)^(1/3)*Rs)"},
   74:{'name':"s74",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(2)^(1/3)*Rs)"},
   75:{'name':"s75",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*(4)^(1/3)*Rs)"},
   76:{'name':"s76",'type':"3D",'dif':"KB*T/(6*PI*mu_NU*Rs)"},
   77:{'name':"s77",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   78:{'name':"s78",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"}}

rxn_list={
   1:{'reactants':"s1' + s2'",'products':"s8'",'fwd_rate':"kp_LR"},
   2:{'reactants':"s1 + s1",'products':"s9",'fwd_rate':"0.5*kp_LL"},
   3:{'reactants':"s5' + s6'",'products':"s10'",'fwd_rate':"k_Im_enters_NP"},
   4:{'reactants':"s9' + s2'",'products':"s11'",'fwd_rate':"2*kp_LR"},
   5:{'reactants':"s8'",'products':"s1' + s2'",'fwd_rate':"km_LR"},
   6:{'reactants':"s1' + s8'",'products':"s11'",'fwd_rate':"kp_LL"},
   7:{'reactants':"s8' + s8'",'products':"s12'",'fwd_rate':"0.5*kp_LL"},
   8:{'reactants':"s9",'products':"s1 + s1",'fwd_rate':"km_LL"},
   9:{'reactants':"s10'",'products':"s5' + s6'",'fwd_rate':"k_Im_exits_NP"},
   10:{'reactants':"s10'",'products':"s13'",'fwd_rate':"k_Im_cross_NP"},
   11:{'reactants':"s11' + s2'",'products':"s12'",'fwd_rate':"kp_LR"},
   12:{'reactants':"s11'",'products':"s9' + s2'",'fwd_rate':"km_LR"},
   13:{'reactants':"s12'",'products':"s11' + s2'",'fwd_rate':"2*km_LR"},
   14:{'reactants':"s11'",'products':"s8' + s1'",'fwd_rate':"km_LL"},
   15:{'reactants':"s12'",'products':"s8' + s8'",'fwd_rate':"km_LL"},
   16:{'reactants':"s12'",'products':"s14'",'fwd_rate':"k_R_endo"},
   17:{'reactants':"s12'",'products':"s15'",'fwd_rate':"2*k_R_transphos"},
   18:{'reactants':"s13'",'products':"s16, + s6'",'fwd_rate':"k_Im_exits_NP"},
   19:{'reactants':"s13'",'products':"s10'",'fwd_rate':"k_Im_cross_NP"},
   20:{'reactants':"s14'",'products':"s17' + s18'",'fwd_rate':"2*km_LR"},
   21:{'reactants':"s15'",'products':"s19' + s2'",'fwd_rate':"km_LR"},
   22:{'reactants':"s15'",'products':"s11' + s20'",'fwd_rate':"km_LR"},
   23:{'reactants':"s14'",'products':"s21' + s21'",'fwd_rate':"km_LL"},
   24:{'reactants':"s15'",'products':"s8' + s22'",'fwd_rate':"km_LL"},
   25:{'reactants':"s15'",'products':"s23'",'fwd_rate':"k_R_endo"},
   26:{'reactants':"s14'",'products':"s12'",'fwd_rate':"k_recycle"},
   27:{'reactants':"s14'",'products':"s23'",'fwd_rate':"2*k_R_transphos"},
   28:{'reactants':"s15'",'products':"s24'",'fwd_rate':"k_R_transphos"},
   29:{'reactants':"s15'",'products':"s12'",'fwd_rate':"k_R_dephos"},
   30:{'reactants':"s15' + s3,",'products':"s25'",'fwd_rate':"kp_R_TF"},
   31:{'reactants':"s16, + s6'",'products':"s13'",'fwd_rate':"k_Im_enters_NP"},
   32:{'reactants':"s1' + s20'",'products':"s22'",'fwd_rate':"kp_LR"},
   33:{'reactants':"s9' + s20'",'products':"s19'",'fwd_rate':"2*kp_LR"},
   34:{'reactants':"s11' + s20'",'products':"s15'",'fwd_rate':"kp_LR"},
   35:{'reactants':"s17' + s18'",'products':"s14'",'fwd_rate':"kp_LR"},
   36:{'reactants':"s19' + s2'",'products':"s15'",'fwd_rate':"kp_LR"},
   37:{'reactants':"s19' + s20'",'products':"s24'",'fwd_rate':"kp_LR"},
   38:{'reactants':"s17'",'products':"s26, + s18'",'fwd_rate':"km_LR"},
   39:{'reactants':"s19'",'products':"s9' + s20'",'fwd_rate':"km_LR"},
   40:{'reactants':"s21'",'products':"s27, + s18'",'fwd_rate':"km_LR"},
   41:{'reactants':"s22'",'products':"s1' + s20'",'fwd_rate':"km_LR"},
   42:{'reactants':"s23'",'products':"s28' + s18'",'fwd_rate':"km_LR"},
   43:{'reactants':"s23'",'products':"s17' + s29'",'fwd_rate':"km_LR"},
   44:{'reactants':"s24'",'products':"s19' + s20'",'fwd_rate':"2*km_LR"},
   45:{'reactants':"s25'",'products':"s30' + s2'",'fwd_rate':"km_LR"},
   46:{'reactants':"s25'",'products':"s11' + s31'",'fwd_rate':"km_LR"},
   47:{'reactants':"s1' + s22'",'products':"s19'",'fwd_rate':"kp_LL"},
   48:{'reactants':"s8' + s22'",'products':"s15'",'fwd_rate':"kp_LL"},
   49:{'reactants':"s21' + s21'",'products':"s14'",'fwd_rate':"0.5*kp_LL"},
   50:{'reactants':"s22' + s22'",'products':"s24'",'fwd_rate':"0.5*kp_LL"},
   51:{'reactants':"s17'",'products':"s21' + s27,",'fwd_rate':"km_LL"},
   52:{'reactants':"s19'",'products':"s22' + s1'",'fwd_rate':"km_LL"},
   53:{'reactants':"s23'",'products':"s21' + s32'",'fwd_rate':"km_LL"},
   54:{'reactants':"s24'",'products':"s22' + s22'",'fwd_rate':"km_LL"},
   55:{'reactants':"s25'",'products':"s8' + s33'",'fwd_rate':"km_LL"},
   56:{'reactants':"s24'",'products':"s34'",'fwd_rate':"k_R_endo"},
   57:{'reactants':"s25'",'products':"s35'",'fwd_rate':"k_R_endo"},
   58:{'reactants':"s17'",'products':"s11'",'fwd_rate':"k_recycle"},
   59:{'reactants':"s18'",'products':"s2'",'fwd_rate':"k_recycle"},
   60:{'reactants':"s21'",'products':"s8'",'fwd_rate':"k_recycle"},
   61:{'reactants':"s23'",'products':"s15'",'fwd_rate':"k_recycle"},
   62:{'reactants':"s23'",'products':"s34'",'fwd_rate':"k_R_transphos"},
   63:{'reactants':"s25'",'products':"s36'",'fwd_rate':"k_R_transphos"},
   64:{'reactants':"s19'",'products':"s11'",'fwd_rate':"k_R_dephos"},
   65:{'reactants':"s20'",'products':"s2'",'fwd_rate':"k_R_dephos"},
   66:{'reactants':"s22'",'products':"s8'",'fwd_rate':"k_R_dephos"},
   67:{'reactants':"s23'",'products':"s14'",'fwd_rate':"k_R_dephos"},
   68:{'reactants':"s24'",'products':"s15'",'fwd_rate':"2*k_R_dephos"},
   69:{'reactants':"s19' + s3,",'products':"s30'",'fwd_rate':"kp_R_TF"},
   70:{'reactants':"s20' + s3,",'products':"s31'",'fwd_rate':"kp_R_TF"},
   71:{'reactants':"s22' + s3,",'products':"s33'",'fwd_rate':"kp_R_TF"},
   72:{'reactants':"s23' + s3'",'products':"s35'",'fwd_rate':"kp_R_TF"},
   73:{'reactants':"s24' + s3,",'products':"s36'",'fwd_rate':"2*kp_R_TF"},
   74:{'reactants':"s25'",'products':"s15' + s3,",'fwd_rate':"km_R_TF"},
   75:{'reactants':"s1' + s31'",'products':"s33'",'fwd_rate':"kp_LR"},
   76:{'reactants':"s9' + s31'",'products':"s30'",'fwd_rate':"2*kp_LR"},
   77:{'reactants':"s11' + s31'",'products':"s25'",'fwd_rate':"kp_LR"},
   78:{'reactants':"s17' + s29'",'products':"s23'",'fwd_rate':"kp_LR"},
   79:{'reactants':"s19' + s31'",'products':"s36'",'fwd_rate':"kp_LR"},
   80:{'reactants':"s26, + s18'",'products':"s17'",'fwd_rate':"2*kp_LR"},
   81:{'reactants':"s26, + s29'",'products':"s28'",'fwd_rate':"2*kp_LR"},
   82:{'reactants':"s27, + s18'",'products':"s21'",'fwd_rate':"kp_LR"},
   83:{'reactants':"s27, + s29'",'products':"s32'",'fwd_rate':"kp_LR"},
   84:{'reactants':"s28' + s18'",'products':"s23'",'fwd_rate':"kp_LR"},
   85:{'reactants':"s28' + s29'",'products':"s34'",'fwd_rate':"kp_LR"},
   86:{'reactants':"s30' + s2'",'products':"s25'",'fwd_rate':"kp_LR"},
   87:{'reactants':"s30' + s20'",'products':"s36'",'fwd_rate':"kp_LR"},
   88:{'reactants':"s30' + s31'",'products':"s37'",'fwd_rate':"kp_LR"},
   89:{'reactants':"s28'",'products':"s26, + s29'",'fwd_rate':"km_LR"},
   90:{'reactants':"s30'",'products':"s9' + s31'",'fwd_rate':"km_LR"},
   91:{'reactants':"s32'",'products':"s27, + s29'",'fwd_rate':"km_LR"},
   92:{'reactants':"s33'",'products':"s1' + s31'",'fwd_rate':"km_LR"},
   93:{'reactants':"s34'",'products':"s28' + s29'",'fwd_rate':"2*km_LR"},
   94:{'reactants':"s35'",'products':"s38' + s18'",'fwd_rate':"km_LR"},
   95:{'reactants':"s35'",'products':"s17' + s39'",'fwd_rate':"km_LR"},
   96:{'reactants':"s36'",'products':"s30' + s20'",'fwd_rate':"km_LR"},
   97:{'reactants':"s36'",'products':"s19' + s31'",'fwd_rate':"km_LR"},
   98:{'reactants':"s1' + s33'",'products':"s30'",'fwd_rate':"kp_LL"},
   99:{'reactants':"s8' + s33'",'products':"s25'",'fwd_rate':"kp_LL"},
   100:{'reactants':"s21' + s27,",'products':"s17'",'fwd_rate':"kp_LL"},
   101:{'reactants':"s21' + s32'",'products':"s23'",'fwd_rate':"kp_LL"},
   102:{'reactants':"s22' + s33'",'products':"s36'",'fwd_rate':"kp_LL"},
   103:{'reactants':"s27 + s27",'products':"s26",'fwd_rate':"0.5*kp_LL"},
   104:{'reactants':"s27, + s32'",'products':"s28'",'fwd_rate':"kp_LL"},
   105:{'reactants':"s32' + s32'",'products':"s34'",'fwd_rate':"0.5*kp_LL"},
   106:{'reactants':"s33' + s33'",'products':"s37'",'fwd_rate':"0.5*kp_LL"},
   107:{'reactants':"s26",'products':"s27 + s27",'fwd_rate':"km_LL"},
   108:{'reactants':"s28'",'products':"s32' + s27,",'fwd_rate':"km_LL"},
   109:{'reactants':"s30'",'products':"s33' + s1'",'fwd_rate':"km_LL"},
   110:{'reactants':"s34'",'products':"s32' + s32'",'fwd_rate':"km_LL"},
   111:{'reactants':"s35'",'products':"s21' + s40'",'fwd_rate':"km_LL"},
   112:{'reactants':"s36'",'products':"s22' + s33'",'fwd_rate':"km_LL"},
   113:{'reactants':"s36'",'products':"s41'",'fwd_rate':"k_R_endo"},
   114:{'reactants':"s28'",'products':"s19'",'fwd_rate':"k_recycle"},
   115:{'reactants':"s29'",'products':"s20'",'fwd_rate':"k_recycle"},
   116:{'reactants':"s32'",'products':"s22'",'fwd_rate':"k_recycle"},
   117:{'reactants':"s34'",'products':"s24'",'fwd_rate':"k_recycle"},
   118:{'reactants':"s35'",'products':"s25'",'fwd_rate':"k_recycle"},
   119:{'reactants':"s26",'products':"s9",'fwd_rate':"k_recycle"},
   120:{'reactants':"s27",'products':"s1",'fwd_rate':"k_recycle"},
   121:{'reactants':"s35'",'products':"s41'",'fwd_rate':"k_R_transphos"},
   122:{'reactants':"s28'",'products':"s17'",'fwd_rate':"k_R_dephos"},
   123:{'reactants':"s29'",'products':"s18'",'fwd_rate':"k_R_dephos"},
   124:{'reactants':"s32'",'products':"s21'",'fwd_rate':"k_R_dephos"},
   125:{'reactants':"s34'",'products':"s23'",'fwd_rate':"2*k_R_dephos"},
   126:{'reactants':"s36'",'products':"s25'",'fwd_rate':"k_R_dephos"},
   127:{'reactants':"s28' + s3'",'products':"s38'",'fwd_rate':"kp_R_TF"},
   128:{'reactants':"s29' + s3'",'products':"s39'",'fwd_rate':"kp_R_TF"},
   129:{'reactants':"s32' + s3'",'products':"s40'",'fwd_rate':"kp_R_TF"},
   130:{'reactants':"s34' + s3'",'products':"s41'",'fwd_rate':"2*kp_R_TF"},
   131:{'reactants':"s36' + s3,",'products':"s37'",'fwd_rate':"kp_R_TF"},
   132:{'reactants':"s30'",'products':"s19' + s3,",'fwd_rate':"km_R_TF"},
   133:{'reactants':"s31'",'products':"s20' + s3,",'fwd_rate':"km_R_TF"},
   134:{'reactants':"s33'",'products':"s22' + s3,",'fwd_rate':"km_R_TF"},
   135:{'reactants':"s35'",'products':"s23' + s3'",'fwd_rate':"km_R_TF"},
   136:{'reactants':"s36'",'products':"s24' + s3,",'fwd_rate':"km_R_TF"},
   137:{'reactants':"s17' + s39'",'products':"s35'",'fwd_rate':"kp_LR"},
   138:{'reactants':"s26, + s39'",'products':"s38'",'fwd_rate':"2*kp_LR"},
   139:{'reactants':"s27, + s39'",'products':"s40'",'fwd_rate':"kp_LR"},
   140:{'reactants':"s28' + s39'",'products':"s41'",'fwd_rate':"kp_LR"},
   141:{'reactants':"s38' + s18'",'products':"s35'",'fwd_rate':"kp_LR"},
   142:{'reactants':"s38' + s29'",'products':"s41'",'fwd_rate':"kp_LR"},
   143:{'reactants':"s38' + s39'",'products':"s42'",'fwd_rate':"kp_LR"},
   144:{'reactants':"s37'",'products':"s30' + s31'",'fwd_rate':"2*km_LR"},
   145:{'reactants':"s38'",'products':"s26, + s39'",'fwd_rate':"km_LR"},
   146:{'reactants':"s40'",'products':"s27, + s39'",'fwd_rate':"km_LR"},
   147:{'reactants':"s41'",'products':"s38' + s29'",'fwd_rate':"km_LR"},
   148:{'reactants':"s41'",'products':"s28' + s39'",'fwd_rate':"km_LR"},
   149:{'reactants':"s21' + s40'",'products':"s35'",'fwd_rate':"kp_LL"},
   150:{'reactants':"s27, + s40'",'products':"s38'",'fwd_rate':"kp_LL"},
   151:{'reactants':"s32' + s40'",'products':"s41'",'fwd_rate':"kp_LL"},
   152:{'reactants':"s40' + s40'",'products':"s42'",'fwd_rate':"0.5*kp_LL"},
   153:{'reactants':"s37'",'products':"s33' + s33'",'fwd_rate':"km_LL"},
   154:{'reactants':"s38'",'products':"s40' + s27,",'fwd_rate':"km_LL"},
   155:{'reactants':"s41'",'products':"s32' + s40'",'fwd_rate':"km_LL"},
   156:{'reactants':"s37'",'products':"s42'",'fwd_rate':"k_R_endo"},
   157:{'reactants':"s38'",'products':"s30'",'fwd_rate':"k_recycle"},
   158:{'reactants':"s39'",'products':"s31'",'fwd_rate':"k_recycle"},
   159:{'reactants':"s40'",'products':"s33'",'fwd_rate':"k_recycle"},
   160:{'reactants':"s41'",'products':"s36'",'fwd_rate':"k_recycle"},
   161:{'reactants':"s41'",'products':"s35'",'fwd_rate':"k_R_dephos"},
   162:{'reactants':"s41' + s3'",'products':"s42'",'fwd_rate':"kp_R_TF"},
   163:{'reactants':"s37'",'products':"s36' + s3,",'fwd_rate':"2*km_R_TF"},
   164:{'reactants':"s38'",'products':"s28' + s3'",'fwd_rate':"km_R_TF"},
   165:{'reactants':"s39'",'products':"s29' + s3'",'fwd_rate':"km_R_TF"},
   166:{'reactants':"s40'",'products':"s32' + s3'",'fwd_rate':"km_R_TF"},
   167:{'reactants':"s41'",'products':"s34' + s3'",'fwd_rate':"km_R_TF"},
   168:{'reactants':"s37'",'products':"s43'",'fwd_rate':"2*k_TF_transphos"},
   169:{'reactants':"s42'",'products':"s38' + s39'",'fwd_rate':"2*km_LR"},
   170:{'reactants':"s43'",'products':"s44' + s31'",'fwd_rate':"km_LR"},
   171:{'reactants':"s43'",'products':"s30' + s45'",'fwd_rate':"km_LR"},
   172:{'reactants':"s42'",'products':"s40' + s40'",'fwd_rate':"km_LL"},
   173:{'reactants':"s43'",'products':"s33' + s46'",'fwd_rate':"km_LL"},
   174:{'reactants':"s43'",'products':"s47'",'fwd_rate':"k_R_endo"},
   175:{'reactants':"s42'",'products':"s37'",'fwd_rate':"k_recycle"},
   176:{'reactants':"s42'",'products':"s41' + s3'",'fwd_rate':"2*km_R_TF"},
   177:{'reactants':"s43'",'products':"s48' + s3,",'fwd_rate':"km_R_TF"},
   178:{'reactants':"s43'",'products':"s36' + s49,",'fwd_rate':"km_R_TFp"},
   179:{'reactants':"s42'",'products':"s47'",'fwd_rate':"2*k_TF_transphos"},
   180:{'reactants':"s43'",'products':"s50'",'fwd_rate':"k_TF_transphos"},
   181:{'reactants':"s43'",'products':"s37'",'fwd_rate':"k_TF_dephos"},
   182:{'reactants':"s1' + s45'",'products':"s46'",'fwd_rate':"kp_LR"},
   183:{'reactants':"s9' + s45'",'products':"s44'",'fwd_rate':"2*kp_LR"},
   184:{'reactants':"s11' + s45'",'products':"s51'",'fwd_rate':"kp_LR"},
   185:{'reactants':"s19' + s45'",'products':"s48'",'fwd_rate':"kp_LR"},
   186:{'reactants':"s30' + s45'",'products':"s43'",'fwd_rate':"kp_LR"},
   187:{'reactants':"s44' + s2'",'products':"s51'",'fwd_rate':"kp_LR"},
   188:{'reactants':"s44' + s20'",'products':"s48'",'fwd_rate':"kp_LR"},
   189:{'reactants':"s44' + s31'",'products':"s43'",'fwd_rate':"kp_LR"},
   190:{'reactants':"s44' + s45'",'products':"s50'",'fwd_rate':"kp_LR"},
   191:{'reactants':"s44'",'products':"s9' + s45'",'fwd_rate':"km_LR"},
   192:{'reactants':"s46'",'products':"s1' + s45'",'fwd_rate':"km_LR"},
   193:{'reactants':"s47'",'products':"s52' + s39'",'fwd_rate':"km_LR"},
   194:{'reactants':"s47'",'products':"s38' + s53'",'fwd_rate':"km_LR"},
   195:{'reactants':"s48'",'products':"s44' + s20'",'fwd_rate':"km_LR"},
   196:{'reactants':"s48'",'products':"s19' + s45'",'fwd_rate':"km_LR"},
   197:{'reactants':"s50'",'products':"s44' + s45'",'fwd_rate':"2*km_LR"},
   198:{'reactants':"s1' + s46'",'products':"s44'",'fwd_rate':"kp_LL"},
   199:{'reactants':"s8' + s46'",'products':"s51'",'fwd_rate':"kp_LL"},
   200:{'reactants':"s22' + s46'",'products':"s48'",'fwd_rate':"kp_LL"},
   201:{'reactants':"s33' + s46'",'products':"s43'",'fwd_rate':"kp_LL"},
   202:{'reactants':"s46' + s46'",'products':"s50'",'fwd_rate':"0.5*kp_LL"},
   203:{'reactants':"s44'",'products':"s46' + s1'",'fwd_rate':"km_LL"},
   204:{'reactants':"s47'",'products':"s40' + s54'",'fwd_rate':"km_LL"},
   205:{'reactants':"s48'",'products':"s22' + s46'",'fwd_rate':"km_LL"},
   206:{'reactants':"s50'",'products':"s46' + s46'",'fwd_rate':"km_LL"},
   207:{'reactants':"s48'",'products':"s55'",'fwd_rate':"k_R_endo"},
   208:{'reactants':"s50'",'products':"s56'",'fwd_rate':"k_R_endo"},
   209:{'reactants':"s47'",'products':"s43'",'fwd_rate':"k_recycle"},
   210:{'reactants':"s48'",'products':"s51'",'fwd_rate':"k_R_dephos"},
   211:{'reactants':"s48' + s3,",'products':"s43'",'fwd_rate':"kp_R_TF"},
   212:{'reactants':"s47'",'products':"s55' + s3'",'fwd_rate':"km_R_TF"},
   213:{'reactants':"s15' + s49,",'products':"s51'",'fwd_rate':"kp_R_TFp"},
   214:{'reactants':"s19' + s49,",'products':"s44'",'fwd_rate':"kp_R_TFp"},
   215:{'reactants':"s20' + s49,",'products':"s45'",'fwd_rate':"kp_R_TFp"},
   216:{'reactants':"s22' + s49,",'products':"s46'",'fwd_rate':"kp_R_TFp"},
   217:{'reactants':"s23' + s49'",'products':"s57'",'fwd_rate':"kp_R_TFp"},
   218:{'reactants':"s24' + s49,",'products':"s48'",'fwd_rate':"2*kp_R_TFp"},
   219:{'reactants':"s28' + s49'",'products':"s52'",'fwd_rate':"kp_R_TFp"},
   220:{'reactants':"s29' + s49'",'products':"s53'",'fwd_rate':"kp_R_TFp"},
   221:{'reactants':"s32' + s49'",'products':"s54'",'fwd_rate':"kp_R_TFp"},
   222:{'reactants':"s34' + s49'",'products':"s55'",'fwd_rate':"2*kp_R_TFp"},
   223:{'reactants':"s36' + s49,",'products':"s43'",'fwd_rate':"kp_R_TFp"},
   224:{'reactants':"s41' + s49'",'products':"s47'",'fwd_rate':"kp_R_TFp"},
   225:{'reactants':"s48' + s49,",'products':"s50'",'fwd_rate':"kp_R_TFp"},
   226:{'reactants':"s44'",'products':"s19' + s49,",'fwd_rate':"km_R_TFp"},
   227:{'reactants':"s45'",'products':"s20' + s49,",'fwd_rate':"km_R_TFp"},
   228:{'reactants':"s46'",'products':"s22' + s49,",'fwd_rate':"km_R_TFp"},
   229:{'reactants':"s47'",'products':"s41' + s49'",'fwd_rate':"km_R_TFp"},
   230:{'reactants':"s48'",'products':"s24' + s49,",'fwd_rate':"km_R_TFp"},
   231:{'reactants':"s50'",'products':"s48' + s49,",'fwd_rate':"2*km_R_TFp"},
   232:{'reactants':"s47'",'products':"s56'",'fwd_rate':"k_TF_transphos"},
   233:{'reactants':"s44'",'products':"s30'",'fwd_rate':"k_TF_dephos"},
   234:{'reactants':"s45'",'products':"s31'",'fwd_rate':"k_TF_dephos"},
   235:{'reactants':"s46'",'products':"s33'",'fwd_rate':"k_TF_dephos"},
   236:{'reactants':"s47'",'products':"s42'",'fwd_rate':"k_TF_dephos"},
   237:{'reactants':"s48'",'products':"s36'",'fwd_rate':"k_TF_dephos"},
   238:{'reactants':"s49",'products':"s3",'fwd_rate':"k_TF_dephos"},
   239:{'reactants':"s50'",'products':"s43'",'fwd_rate':"2*k_TF_dephos"},
   240:{'reactants':"s49 + s49",'products':"s58",'fwd_rate':"0.5*kp_TF_TF"},
   241:{'reactants':"s17' + s53'",'products':"s57'",'fwd_rate':"kp_LR"},
   242:{'reactants':"s26, + s53'",'products':"s52'",'fwd_rate':"2*kp_LR"},
   243:{'reactants':"s27, + s53'",'products':"s54'",'fwd_rate':"kp_LR"},
   244:{'reactants':"s28' + s53'",'products':"s55'",'fwd_rate':"kp_LR"},
   245:{'reactants':"s38' + s53'",'products':"s47'",'fwd_rate':"kp_LR"},
   246:{'reactants':"s52' + s18'",'products':"s57'",'fwd_rate':"kp_LR"},
   247:{'reactants':"s52' + s29'",'products':"s55'",'fwd_rate':"kp_LR"},
   248:{'reactants':"s52' + s39'",'products':"s47'",'fwd_rate':"kp_LR"},
   249:{'reactants':"s52' + s53'",'products':"s56'",'fwd_rate':"kp_LR"},
   250:{'reactants':"s51'",'products':"s44' + s2'",'fwd_rate':"km_LR"},
   251:{'reactants':"s51'",'products':"s11' + s45'",'fwd_rate':"km_LR"},
   252:{'reactants':"s52'",'products':"s26, + s53'",'fwd_rate':"km_LR"},
   253:{'reactants':"s54'",'products':"s27, + s53'",'fwd_rate':"km_LR"},
   254:{'reactants':"s55'",'products':"s52' + s29'",'fwd_rate':"km_LR"},
   255:{'reactants':"s55'",'products':"s28' + s53'",'fwd_rate':"km_LR"},
   256:{'reactants':"s56'",'products':"s52' + s53'",'fwd_rate':"2*km_LR"},
   257:{'reactants':"s57'",'products':"s52' + s18'",'fwd_rate':"km_LR"},
   258:{'reactants':"s57'",'products':"s17' + s53'",'fwd_rate':"km_LR"},
   259:{'reactants':"s21' + s54'",'products':"s57'",'fwd_rate':"kp_LL"},
   260:{'reactants':"s27, + s54'",'products':"s52'",'fwd_rate':"kp_LL"},
   261:{'reactants':"s32' + s54'",'products':"s55'",'fwd_rate':"kp_LL"},
   262:{'reactants':"s40' + s54'",'products':"s47'",'fwd_rate':"kp_LL"},
   263:{'reactants':"s54' + s54'",'products':"s56'",'fwd_rate':"0.5*kp_LL"},
   264:{'reactants':"s51'",'products':"s8' + s46'",'fwd_rate':"km_LL"},
   265:{'reactants':"s52'",'products':"s54' + s27,",'fwd_rate':"km_LL"},
   266:{'reactants':"s55'",'products':"s32' + s54'",'fwd_rate':"km_LL"},
   267:{'reactants':"s56'",'products':"s54' + s54'",'fwd_rate':"km_LL"},
   268:{'reactants':"s57'",'products':"s21' + s54'",'fwd_rate':"km_LL"},
   269:{'reactants':"s51'",'products':"s57'",'fwd_rate':"k_R_endo"},
   270:{'reactants':"s52'",'products':"s44'",'fwd_rate':"k_recycle"},
   271:{'reactants':"s53'",'products':"s45'",'fwd_rate':"k_recycle"},
   272:{'reactants':"s54'",'products':"s46'",'fwd_rate':"k_recycle"},
   273:{'reactants':"s55'",'products':"s48'",'fwd_rate':"k_recycle"},
   274:{'reactants':"s56'",'products':"s50'",'fwd_rate':"k_recycle"},
   275:{'reactants':"s57'",'products':"s51'",'fwd_rate':"k_recycle"},
   276:{'reactants':"s51'",'products':"s48'",'fwd_rate':"k_R_transphos"},
   277:{'reactants':"s57'",'products':"s55'",'fwd_rate':"k_R_transphos"},
   278:{'reactants':"s55'",'products':"s57'",'fwd_rate':"k_R_dephos"},
   279:{'reactants':"s55' + s3'",'products':"s47'",'fwd_rate':"kp_R_TF"},
   280:{'reactants':"s55' + s49'",'products':"s56'",'fwd_rate':"kp_R_TFp"},
   281:{'reactants':"s51'",'products':"s15' + s49,",'fwd_rate':"km_R_TFp"},
   282:{'reactants':"s52'",'products':"s28' + s49'",'fwd_rate':"km_R_TFp"},
   283:{'reactants':"s53'",'products':"s29' + s49'",'fwd_rate':"km_R_TFp"},
   284:{'reactants':"s54'",'products':"s32' + s49'",'fwd_rate':"km_R_TFp"},
   285:{'reactants':"s55'",'products':"s34' + s49'",'fwd_rate':"km_R_TFp"},
   286:{'reactants':"s56'",'products':"s55' + s49'",'fwd_rate':"2*km_R_TFp"},
   287:{'reactants':"s57'",'products':"s23' + s49'",'fwd_rate':"km_R_TFp"},
   288:{'reactants':"s51'",'products':"s25'",'fwd_rate':"k_TF_dephos"},
   289:{'reactants':"s52'",'products':"s38'",'fwd_rate':"k_TF_dephos"},
   290:{'reactants':"s53'",'products':"s39'",'fwd_rate':"k_TF_dephos"},
   291:{'reactants':"s54'",'products':"s40'",'fwd_rate':"k_TF_dephos"},
   292:{'reactants':"s55'",'products':"s41'",'fwd_rate':"k_TF_dephos"},
   293:{'reactants':"s56'",'products':"s47'",'fwd_rate':"2*k_TF_dephos"},
   294:{'reactants':"s57'",'products':"s35'",'fwd_rate':"k_TF_dephos"},
   295:{'reactants':"s58",'products':"s49 + s49",'fwd_rate':"km_TF_TF"},
   296:{'reactants':"s58 + s5",'products':"s59",'fwd_rate':"k_Im_bind_CP"},
   297:{'reactants':"s58' + s10'",'products':"s60'",'fwd_rate':"k_Im_bind_CP"},
   298:{'reactants':"s59",'products':"s58 + s5",'fwd_rate':"k_Im_unbind_CP"},
   299:{'reactants':"s60'",'products':"s58' + s10'",'fwd_rate':"k_Im_unbind_CP"},
   300:{'reactants':"s59' + s6'",'products':"s60'",'fwd_rate':"k_Im_enters_NP"},
   301:{'reactants':"s60'",'products':"s59' + s6'",'fwd_rate':"k_Im_exits_NP"},
   302:{'reactants':"s60'",'products':"s61'",'fwd_rate':"k_Im_cross_NP"},
   303:{'reactants':"s61'",'products':"s62, + s13'",'fwd_rate':"k_Im_unbind_NU"},
   304:{'reactants':"s61'",'products':"s63, + s6'",'fwd_rate':"k_Im_exits_NP"},
   305:{'reactants':"s61'",'products':"s60'",'fwd_rate':"k_Im_cross_NP"},
   306:{'reactants':"s62",'products':"s64 + s64",'fwd_rate':"km_TF_TF"},
   307:{'reactants':"s62 + s4",'products':"s65",'fwd_rate':"kp_TF_p1"},
   308:{'reactants':"s62, + s13'",'products':"s61'",'fwd_rate':"k_Im_bind_NU"},
   309:{'reactants':"s62 + s16",'products':"s63",'fwd_rate':"k_Im_bind_NU"},
   310:{'reactants':"s63",'products':"s62 + s16",'fwd_rate':"k_Im_unbind_NU"},
   311:{'reactants':"s63, + s6'",'products':"s61'",'fwd_rate':"k_Im_enters_NP"},
   312:{'reactants':"s64 + s64",'products':"s62",'fwd_rate':"0.5*kp_TF_TF"},
   313:{'reactants':"s65",'products':"s62 + s4",'fwd_rate':"km_TF_p1"},
   314:{'reactants':"s65",'products':"s65 + s66",'fwd_rate':"k_transcribe"},
   315:{'reactants':"s66",'products':"s67",'fwd_rate':"k_mRNA_to_CP"},
   316:{'reactants':"s66",'products':"s7",'fwd_rate':"k_mRNA_deg"},
   317:{'reactants':"s67",'products':"s67 + s68",'fwd_rate':"k_translate"},
   318:{'reactants':"s67",'products':"s7",'fwd_rate':"k_mRNA_deg"},
   319:{'reactants':"s68",'products':"s7",'fwd_rate':"k_P_deg"},
   320:{'reactants':"s68 + s5",'products':"s69",'fwd_rate':"k_Im_bind_CP"},
   321:{'reactants':"s68' + s10'",'products':"s70'",'fwd_rate':"k_Im_bind_CP"},
   322:{'reactants':"s69",'products':"s7 + s5",'fwd_rate':"k_P_deg"},
   323:{'reactants':"s70'",'products':"s7' + s10'",'fwd_rate':"k_P_deg"},
   324:{'reactants':"s69",'products':"s68 + s5",'fwd_rate':"k_Im_unbind_CP"},
   325:{'reactants':"s70'",'products':"s68' + s10'",'fwd_rate':"k_Im_unbind_CP"},
   326:{'reactants':"s69' + s6'",'products':"s70'",'fwd_rate':"k_Im_enters_NP"},
   327:{'reactants':"s70'",'products':"s69' + s6'",'fwd_rate':"k_Im_exits_NP"},
   328:{'reactants':"s70'",'products':"s71'",'fwd_rate':"k_Im_cross_NP"},
   329:{'reactants':"s71'",'products':"s7' + s13'",'fwd_rate':"k_P_deg"},
   330:{'reactants':"s71'",'products':"s72, + s13'",'fwd_rate':"k_Im_unbind_NU"},
   331:{'reactants':"s71'",'products':"s73, + s6'",'fwd_rate':"k_Im_exits_NP"},
   332:{'reactants':"s71'",'products':"s70'",'fwd_rate':"k_Im_cross_NP"},
   333:{'reactants':"s72",'products':"s7",'fwd_rate':"k_P_deg"},
   334:{'reactants':"s73",'products':"s7 + s16",'fwd_rate':"k_P_deg"},
   335:{'reactants':"s72, + s13'",'products':"s71'",'fwd_rate':"k_Im_bind_NU"},
   336:{'reactants':"s72 + s16",'products':"s73",'fwd_rate':"k_Im_bind_NU"},
   337:{'reactants':"s73",'products':"s72 + s16",'fwd_rate':"k_Im_unbind_NU"},
   338:{'reactants':"s73, + s6'",'products':"s71'",'fwd_rate':"k_Im_enters_NP"},
   339:{'reactants':"s72 + s4",'products':"s74",'fwd_rate':"kp_P1_p2"},
   340:{'reactants':"s72 + s65",'products':"s75",'fwd_rate':"kp_P1_p2"},
   341:{'reactants':"s62 + s74",'products':"s75",'fwd_rate':"kp_TF_p1"},
   342:{'reactants':"s75",'products':"s62 + s74",'fwd_rate':"km_TF_p1"},
   343:{'reactants':"s75",'products':"s75 + s66",'fwd_rate':"k_transcribe"},
   344:{'reactants':"s74",'products':"s74 + s76",'fwd_rate':"k_transcribe"},
   345:{'reactants':"s75",'products':"s75 + s76",'fwd_rate':"k_transcribe"},
   346:{'reactants':"s74",'products':"s7 + s4",'fwd_rate':"k_P_deg"},
   347:{'reactants':"s75",'products':"s7 + s65",'fwd_rate':"k_P_deg"},
   348:{'reactants':"s74",'products':"s72 + s4",'fwd_rate':"km_P1_p2"},
   349:{'reactants':"s75",'products':"s72 + s65",'fwd_rate':"km_P1_p2"},
   350:{'reactants':"s76",'products':"s77",'fwd_rate':"k_mRNA_to_CP"},
   351:{'reactants':"s76",'products':"s7",'fwd_rate':"k_mRNA_deg"},
   352:{'reactants':"s77",'products':"s77 + s78",'fwd_rate':"k_translate"},
   353:{'reactants':"s77",'products':"s7",'fwd_rate':"k_mRNA_deg"},
   354:{'reactants':"s78",'products':"s7",'fwd_rate':"k_P_deg"}}

rel_list={
   1:{'name':"Release_Site_s1",'molecule':"s1",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"L0/(Nav*vol_EC)",'object_expr':" - CP[ALL]"},
   2:{'name':"Release_Site_s2",'molecule':"s2",'shape':"OBJECT",'orient':"\'",'quantity_type':"DENSITY",'quantity_expr':"R0/vol_PM",'object_expr':"CP[PM]"},
   3:{'name':"Release_Site_s3",'molecule':"s3",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"TF0/(Nav*vol_CP)",'object_expr':"CP[ALL] - CP[ALL] - CP[ALL]"},
   4:{'name':"Release_Site_s4",'molecule':"s4",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"DNA0/(Nav*vol_NU)",'object_expr':"CP"},
   5:{'name':"Release_Site_s5",'molecule':"s5",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"Im0/(Nav*vol_CP)",'object_expr':"CP[ALL] - CP[ALL] - CP[ALL]"},
   6:{'name':"Release_Site_s6",'molecule':"s6",'shape':"OBJECT",'orient':"\'",'quantity_type':"DENSITY",'quantity_expr':"NP0/vol_NM",'object_expr':"CP[NM]"}}