#include "BnglWriter.hpp"

#include <sstream>
#include <iomanip>
#include <cmath>

namespace bng::io {

std::string BnglWriter::formatNumber(double value) {
    if (!std::isfinite(value)) return "0";

    // Use scientific notation for very large or very small numbers
    if (std::abs(value) > 1e6 || (std::abs(value) < 1e-3 && value != 0.0)) {
        std::ostringstream oss;
        oss << std::scientific << std::setprecision(6) << value;
        return oss.str();
    }

    // For normal numbers, use fixed notation
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(6) << value;
    std::string str = oss.str();

    // Remove trailing zeros
    str.erase(str.find_last_not_of('0') + 1, std::string::npos);
    if (str.back() == '.') str.pop_back();

    return str;
}

std::string BnglWriter::write(const ast::Model& model, const engine::GeneratedNetwork* network) {
    Options options;
    options.includeComments = true;
    options.includeActions = false;
    options.evaluateExpressions = false;
    return write(model, network, options);
}

std::string BnglWriter::write(const ast::Model& model, const engine::GeneratedNetwork* network, const Options& options) {
    std::ostringstream bngl;

    if (options.includeComments) {
        bngl << "# Generated by BioNetGen C++\n";
        bngl << "# Model: " << model.getModelName() << "\n\n";
    }

    bngl << "begin model\n\n";

    // Parameters
    bngl << writeParameters(model, options);

    // Compartments
    if (!model.getCompartments().empty()) {
        bngl << writeCompartments(model);
    }

    // Molecule types
    if (!model.getMoleculeTypes().empty()) {
        bngl << writeMoleculeTypes(model);
    }

    // Seed species
    if (!model.getSeedSpecies().empty()) {
        bngl << writeSeedSpecies(model);
    }

    // Observables
    if (!model.getObservables().empty()) {
        bngl << writeObservables(model);
    }

    // Functions
    if (!model.getFunctions().empty()) {
        bngl << writeFunctions(model);
    }

    // Reaction rules
    if (!model.getReactionRules().empty()) {
        bngl << writeReactionRules(model);
    }

    bngl << "end model\n";

    // Actions
    if (options.includeActions && !model.getActions().empty()) {
        bngl << "\n" << writeActions(model);
    }

    return bngl.str();
}

std::string BnglWriter::writeParameters(const ast::Model& model, const Options& opts) {
    std::ostringstream bngl;
    bngl << "begin parameters\n";

    for (const auto& param : model.getParameters().all()) {
        bngl << "  " << param.getName() << " ";

        if (opts.evaluateExpressions) {
            bngl << formatNumber(param.getValue());
        } else {
            bngl << param.getExpression().toString();
        }

        bngl << "\n";
    }

    bngl << "end parameters\n\n";
    return bngl.str();
}

std::string BnglWriter::writeCompartments(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin compartments\n";

    for (const auto& comp : model.getCompartments()) {
        bngl << "  " << comp.getName()
             << " " << comp.getDimension()
             << " " << formatNumber(comp.getVolume());

        if (!comp.getParent().empty()) {
            bngl << " " << comp.getParent();
        }

        bngl << "\n";
    }

    bngl << "end compartments\n\n";
    return bngl.str();
}

std::string BnglWriter::writeMoleculeTypes(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin molecule types\n";

    for (const auto& mt : model.getMoleculeTypes()) {
        bngl << "  " << mt.getName();

        const auto& components = mt.getComponents();
        if (!components.empty()) {
            bngl << "(";
            for (std::size_t i = 0; i < components.size(); ++i) {
                if (i > 0) bngl << ",";
                bngl << components[i].name;  // ComponentType is a struct with public fields

                if (!components[i].allowedStates.empty()) {
                    for (const auto& state : components[i].allowedStates) {
                        bngl << "~" << state;
                    }
                }
            }
            bngl << ")";
        }

        bngl << "\n";
    }

    bngl << "end molecule types\n\n";
    return bngl.str();
}

std::string BnglWriter::writeSeedSpecies(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin seed species\n";

    for (const auto& seed : model.getSeedSpecies()) {
        // Evaluate amount
        auto amountValue = seed.getAmount().evaluate([&](const std::string& name) {
            return model.getParameters().evaluate(name);
        }, 0.0);

        bngl << "  " << seed.getPattern()
             << " " << formatNumber(amountValue)
             << "\n";
    }

    bngl << "end seed species\n\n";
    return bngl.str();
}

std::string BnglWriter::writeObservables(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin observables\n";

    for (const auto& obs : model.getObservables()) {
        bngl << "  " << obs.getType()
             << " " << obs.getName() << " ";

        // Join patterns with commas
        const auto& patterns = obs.getPatterns();
        for (std::size_t i = 0; i < patterns.size(); ++i) {
            if (i > 0) bngl << ",";
            bngl << patterns[i];
        }

        bngl << "\n";
    }

    bngl << "end observables\n\n";
    return bngl.str();
}

std::string BnglWriter::writeFunctions(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin functions\n";

    for (const auto& func : model.getFunctions()) {
        bngl << "  " << func.getName() << "()";
        bngl << " = " << func.getExpression().toString();
        bngl << "\n";
    }

    bngl << "end functions\n\n";
    return bngl.str();
}

std::string BnglWriter::writeReactionRules(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin reaction rules\n";

    for (const auto& rule : model.getReactionRules()) {
        bngl << "  ";

        if (!rule.getRuleName().empty()) {
            bngl << rule.getRuleName() << ": ";
        }

        // Reactants (these are pattern strings)
        const auto& reactants = rule.getReactants();
        for (std::size_t i = 0; i < reactants.size(); ++i) {
            if (i > 0) bngl << " + ";
            bngl << reactants[i];  // Already strings
        }

        // Arrow
        if (rule.isBidirectional()) {
            bngl << " <-> ";
        } else {
            bngl << " -> ";
        }

        // Products (these are pattern strings)
        const auto& products = rule.getProducts();
        for (std::size_t i = 0; i < products.size(); ++i) {
            if (i > 0) bngl << " + ";
            bngl << products[i];  // Already strings
        }

        // Rates
        const auto& rates = rule.getRates();
        if (!rates.empty()) {
            bngl << " " << rates[0].toString();
            if (rule.isBidirectional() && rates.size() > 1) {
                bngl << ", " << rates[1].toString();
            }
        }

        bngl << "\n";
    }

    bngl << "end reaction rules\n\n";
    return bngl.str();
}

std::string BnglWriter::writeActions(const ast::Model& model) {
    std::ostringstream bngl;
    bngl << "begin actions\n";

    for (const auto& action : model.getActions()) {
        bngl << "  " << action.name << "(";

        // Write arguments
        bool first = true;
        for (const auto& [key, value] : action.arguments) {
            if (!first) bngl << ", ";
            first = false;
            bngl << key << "=>\"" << value << "\"";
        }

        bngl << ")\n";
    }

    bngl << "end actions\n";
    return bngl.str();
}

} // namespace bng::io
