#include "LatexWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <map>
#include <set>

#include <antlr4-runtime.h>
#include "generated/BNGLexer.h"
#include "generated/BNGParser.h"
#include "parser/PatternGraphBuilder.hpp"
#include "core/Ullmann.hpp"

namespace bng::io {

std::string LatexWriter::escapeLatex(const std::string& text) {
    std::string result;
    result.reserve(text.size() * 2);
    for (char c : text) {
        switch (c) {
            case '_': result += "\\_"; break;
            case '&': result += "\\&"; break;
            case '%': result += "\\%"; break;
            case '$': result += "\\$"; break;
            case '#': result += "\\#"; break;
            case '{': result += "\\{"; break;
            case '}': result += "\\}"; break;
            case '~': result += "\\textasciitilde{}"; break;
            case '^': result += "\\textasciicircum{}"; break;
            default: result += c; break;
        }
    }
    return result;
}

std::string LatexWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    std::ostringstream out;

    const std::string modelName = model.getModelName();
    const std::size_t nSpecies = network.species.size();
    const std::size_t nRxns = network.reactions.size();

    // Collect parameter info
    std::vector<std::string> paramNames;
    std::vector<double> paramValues;
    for (const auto& param : model.getParameters().all()) {
        paramNames.push_back(param.getName());
        paramValues.push_back(param.getValue());
    }

    // Compute observable groups
    std::vector<std::pair<std::string, std::vector<std::string>>> observableDefs;
    for (const auto& observable : model.getObservables()) {
        observableDefs.push_back({observable.getName(), observable.getPatterns()});
    }

    // === Document preamble ===
    out << "\\documentclass[11pt]{article}\n";
    out << "\\usepackage{amsmath}\n";
    out << "\\usepackage{booktabs}\n";
    out << "\\usepackage{longtable}\n";
    out << "\\usepackage[version=4]{mhchem}\n";
    out << "\\usepackage[margin=1in]{geometry}\n";
    out << "\n";
    out << "\\title{BioNetGen Model: " << escapeLatex(modelName) << "}\n";
    out << "\\author{Generated by BioNetGen C++}\n";
    out << "\\date{}\n";
    out << "\n";
    out << "\\begin{document}\n";
    out << "\\maketitle\n";
    out << "\n";

    // === Parameters section ===
    out << "\\section{Parameters}\n";
    out << "\n";
    if (!paramNames.empty()) {
        out << "\\begin{longtable}{ll}\n";
        out << "\\toprule\n";
        out << "\\textbf{Parameter} & \\textbf{Value} \\\\\n";
        out << "\\midrule\n";
        out << "\\endhead\n";
        for (std::size_t i = 0; i < paramNames.size(); ++i) {
            out << "\\texttt{" << escapeLatex(paramNames[i]) << "} & $"
                << std::setprecision(15) << paramValues[i] << "$ \\\\\n";
        }
        out << "\\bottomrule\n";
        out << "\\end{longtable}\n";
    } else {
        out << "No parameters defined.\n";
    }
    out << "\n";

    // === Species section ===
    out << "\\section{Species}\n";
    out << "\n";
    if (nSpecies > 0) {
        out << "\\begin{longtable}{rl}\n";
        out << "\\toprule\n";
        out << "\\textbf{Species} & \\textbf{Initial Count} \\\\\n";
        out << "\\midrule\n";
        out << "\\endhead\n";
        for (std::size_t i = 0; i < nSpecies; ++i) {
            const auto& sp = network.species.get(i);
            std::string speciesStr = sp.getSpeciesGraph().toString();
            out << "\\texttt{" << escapeLatex(speciesStr) << "} & $"
                << sp.getAmount() << "$ \\\\\n";
        }
        out << "\\bottomrule\n";
        out << "\\end{longtable}\n";
    } else {
        out << "No species defined.\n";
    }
    out << "\n";

    // === Reactions section ===
    out << "\\section{Reactions}\n";
    out << "\n";
    if (nRxns > 0) {
        for (std::size_t r = 0; r < nRxns; ++r) {
            const auto& rxn = network.reactions.all()[r];

            out << "\\begin{equation}\n";

            // Reactants
            const auto& reactants = rxn.getReactants();
            if (reactants.empty()) {
                out << "  \\varnothing";
            } else {
                for (std::size_t i = 0; i < reactants.size(); ++i) {
                    if (i > 0) out << " + ";
                    std::string name = network.species.get(reactants[i]).getSpeciesGraph().toString();
                    out << "\\text{" << escapeLatex(name) << "}";
                }
            }

            out << " \\xrightarrow{";

            // Rate law
            const std::string& rateLaw = rxn.getRateLaw();
            std::string cleanRate = rateLaw;
            auto localPos = cleanRate.find("|local:");
            if (localPos != std::string::npos) {
                cleanRate = cleanRate.substr(0, localPos);
            }

            double statFactor = rxn.getFactor();
            bool isNumeric = false;
            double rateVal = 0.0;
            try {
                std::size_t pos = 0;
                rateVal = std::stod(cleanRate, &pos);
                if (pos == cleanRate.size()) isNumeric = true;
            } catch (...) {}

            if (isNumeric) {
                double combined = statFactor * rateVal;
                out << combined;
            } else {
                if (std::abs(statFactor - 1.0) > 1e-12) {
                    out << statFactor << " \\cdot ";
                }
                out << "\\text{" << escapeLatex(cleanRate) << "}";
            }

            out << "} ";

            // Products
            const auto& products = rxn.getProducts();
            if (products.empty()) {
                out << "\\varnothing";
            } else {
                for (std::size_t i = 0; i < products.size(); ++i) {
                    if (i > 0) out << " + ";
                    std::string name = network.species.get(products[i]).getSpeciesGraph().toString();
                    out << "\\text{" << escapeLatex(name) << "}";
                }
            }

            out << "\n";
            out << "\\end{equation}\n";
            out << "\n";
        }
    } else {
        out << "No reactions defined.\n";
    }

    // === Observables section ===
    out << "\\section{Observables}\n";
    out << "\n";
    if (!observableDefs.empty()) {
        out << "\\begin{longtable}{ll}\n";
        out << "\\toprule\n";
        out << "\\textbf{Observable} & \\textbf{Pattern(s)} \\\\\n";
        out << "\\midrule\n";
        out << "\\endhead\n";
        for (const auto& [name, patterns] : observableDefs) {
            out << "\\texttt{" << escapeLatex(name) << "} & $";
            for (std::size_t i = 0; i < patterns.size(); ++i) {
                if (i > 0) out << " + ";
                out << "\\text{" << escapeLatex(patterns[i]) << "}";
            }
            out << "$ \\\\\n";
        }
        out << "\\bottomrule\n";
        out << "\\end{longtable}\n";
    } else {
        out << "No observables defined.\n";
    }
    out << "\n";

    out << "\\end{document}\n";

    return out.str();
}

} // namespace bng::io
