#include "MatlabWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <map>
#include <set>

#include <antlr4-runtime.h>
#include "generated/BNGLexer.h"
#include "generated/BNGParser.h"
#include "parser/PatternGraphBuilder.hpp"
#include "core/Ullmann.hpp"

namespace bng::io {

std::string MatlabWriter::makeMatlabFunctionName(const std::string& modelName) {
    std::string name = modelName;
    std::transform(name.begin(), name.end(), name.begin(), [](char c) {
        return std::isalnum(static_cast<unsigned char>(c)) ? c : '_';
    });
    if (!name.empty() && std::isdigit(static_cast<unsigned char>(name[0]))) {
        name = "model_" + name;
    }
    return name.empty() ? "bng_model" : name;
}

std::string MatlabWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    Options opts;
    return write(model, network, opts);
}

std::string MatlabWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network, const Options& opts) {
    std::ostringstream m;

    std::string funcName = makeMatlabFunctionName(model.getModelName());
    const std::size_t nSpecies = network.species.size();
    const std::size_t nRxns = network.reactions.size();

    // Compute observable groups and stoichiometry
    auto groups = computeObservableGroups(model, network);
    auto stoich = computeStoichiometry(network, nSpecies);

    // Collect parameter info
    std::vector<std::string> paramNames;
    std::vector<double> paramValues;
    for (const auto& param : model.getParameters().all()) {
        paramNames.push_back(param.getName());
        paramValues.push_back(param.getValue());
    }

    // Detect fixed species ($ prefix)
    std::vector<bool> fixedSpecies(nSpecies, false);
    for (std::size_t i = 0; i < nSpecies; ++i) {
        fixedSpecies[i] = network.species.get(i).isConstant();
    }

    // Function header (Perl parity: 4 outputs, 4 inputs)
    m << "function [err, timepoints, species_out, observables_out] = " << funcName
      << "(timepoints, species_init, parameters, suppress_plot)\n";
    m << "%% " << funcName << " - MATLAB ODE model\n";
    m << "%% Generated by BioNetGen C++\n";
    m << "%%\n";
    m << "%% Usage:\n";
    m << "%%   [err, timepoints, species_out, observables_out] = " << funcName << "()\n";
    m << "%%   [err, timepoints, species_out, observables_out] = " << funcName << "(timepoints, species_init, parameters)\n\n";

    // Default input handling
    m << "%% Default parameters, initial conditions, and calculation handlers\n";
    m << "if (nargin < 1)\n";
    m << "    timepoints = linspace(" << opts.tStart << ", " << opts.tEnd << ", " << (opts.nSteps + 1) << ")';\n";
    m << "end\n";
    m << "if (nargin < 2)\n";
    m << "    species_init = getInitialSpecies();\n";
    m << "end\n";
    m << "if (nargin < 3)\n";
    m << "    parameters = getDefaultParameters();\n";
    m << "end\n";
    m << "if (nargin < 4)\n";
    m << "    suppress_plot = 0;\n";
    m << "end\n\n";

    // Validate dimensions
    m << "%% Validate input dimensions\n";
    m << "if (length(parameters) ~= " << paramNames.size() << ")\n";
    m << "    error('parameters must have " << paramNames.size() << " elements');\n";
    m << "end\n";
    m << "if (length(species_init) ~= " << nSpecies << ")\n";
    m << "    error('species_init must have " << nSpecies << " elements');\n";
    m << "end\n\n";

    // Number of observables and species
    m << "%% Model dimensions\n";
    m << "n_species = " << nSpecies << ";\n";
    m << "n_observables = " << groups.size() << ";\n";
    m << "n_ratelaws = " << nRxns << ";\n\n";

    // ODE solver options
    m << "%% ODE solver options\n";
    m << "odeopts = odeset(";
    m << "'RelTol', " << opts.rtol;
    m << ", 'AbsTol', " << opts.atol;
    m << ", 'Stats', '" << (opts.stats ? "on" : "off") << "'";
    m << ", 'BDF', '" << (opts.bdf ? "on" : "off") << "'";
    m << ", 'MaxOrder', " << opts.maxOrder;
    if (opts.maxStep > 0.0) {
        m << ", 'MaxStep', " << opts.maxStep;
    }
    m << ");\n\n";

    // Solve
    m << "%% Solve ODE\n";
    m << "try\n";
    m << "    [~, species_out] = ode15s(@(t,y) calc_species_deriv(t, y, parameters), timepoints, species_init, odeopts);\n";
    m << "catch e\n";
    m << "    err = 1;\n";
    m << "    fprintf('Integration error: %s\\n', e.message);\n";
    m << "    timepoints = [];\n";
    m << "    species_out = [];\n";
    m << "    observables_out = [];\n";
    m << "    return;\n";
    m << "end\n\n";

    // Compute observables at each time point
    m << "%% Compute observables at each time point\n";
    m << "observables_out = zeros(length(timepoints), n_observables);\n";
    m << "for t_idx = 1:length(timepoints)\n";
    m << "    observables_out(t_idx, :) = calc_observables(species_out(t_idx, :)', parameters);\n";
    m << "end\n\n";

    // Plot
    m << "%% Plot results\n";
    m << "if (~suppress_plot)\n";
    m << "    figure;\n";
    if (!groups.empty()) {
        m << "    plot(timepoints, observables_out);\n";
        m << "    legend(";
        for (std::size_t i = 0; i < groups.size(); ++i) {
            if (i > 0) m << ", ";
            m << "'" << groups[i].name << "'";
        }
        m << ", 'Location', 'best');\n";
        m << "    ylabel('Number', 'FontSize', 12);\n";
    } else {
        m << "    plot(timepoints, species_out);\n";
        m << "    ylabel('Species Count', 'FontSize', 12);\n";
    }
    m << "    xlabel('Time', 'FontSize', 12);\n";
    m << "    title('" << model.getModelName() << "', 'FontSize', 14);\n";
    m << "end\n\n";

    m << "err = 0;\n";
    m << "return;\n\n";

    // ===== Nested function: getDefaultParameters =====
    m << "%% Default parameters\n";
    m << "function p = getDefaultParameters()\n";
    m << "    p = zeros(" << paramNames.size() << ", 1);\n";
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        m << "    p(" << (i + 1) << ") = " << std::setprecision(15) << paramValues[i]
          << "; % " << paramNames[i] << "\n";
    }
    m << "end\n\n";

    // ===== Nested function: getInitialSpecies =====
    m << "%% Default initial species concentrations\n";
    m << "function y0 = getInitialSpecies()\n";
    m << "    y0 = zeros(" << nSpecies << ", 1);\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        const auto& sp = network.species.get(i);
        m << "    y0(" << (i + 1) << ") = " << sp.getAmount()
          << "; % " << sp.getSpeciesGraph().toString() << "\n";
    }
    m << "end\n\n";

    // ===== Nested function: calc_expressions =====
    m << "%% Calculate expressions from parameters\n";
    m << "function expressions = calc_expressions(parameters)\n";
    m << "    expressions = zeros(" << paramNames.size() << ", 1);\n";
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        // Simple: map parameter value directly to expressions array
        m << "    expressions(" << (i + 1) << ") = parameters(" << (i + 1)
          << "); % " << paramNames[i] << "\n";
    }
    m << "end\n\n";

    // ===== Nested function: calc_observables =====
    m << "%% Calculate observables from species\n";
    m << "function observables = calc_observables(species, parameters)\n";
    m << "    observables = zeros(" << groups.size() << ", 1);\n";
    for (std::size_t g = 0; g < groups.size(); ++g) {
        if (groups[g].entries.empty()) {
            m << "    observables(" << (g + 1) << ") = 0; % " << groups[g].name << "\n";
        } else {
            m << "    observables(" << (g + 1) << ") = ";
            bool first = true;
            for (const auto& [specIdx, weight] : groups[g].entries) {
                if (!first) m << " + ";
                if (weight > 1) {
                    m << weight << "*";
                }
                m << "species(" << (specIdx + 1) << ")";
                first = false;
            }
            m << "; % " << groups[g].name << "\n";
        }
    }
    m << "end\n\n";

    // ===== Nested function: calc_ratelaws =====
    m << "%% Calculate rate laws\n";
    m << "function ratelaws = calc_ratelaws(species, expressions, observables)\n";
    m << "    ratelaws = zeros(" << nRxns << ", 1);\n";
    for (std::size_t r = 0; r < nRxns; ++r) {
        const auto& rxn = network.reactions.all()[r];
        m << "    ratelaws(" << (r + 1) << ") = ";

        // Rate constant
        const std::string& rateLaw = rxn.getRateLaw();
        // Strip |local: suffix
        std::string cleanRate = rateLaw;
        auto localPos = cleanRate.find("|local:");
        if (localPos != std::string::npos) {
            cleanRate = cleanRate.substr(0, localPos);
        }

        double statFactor = rxn.getFactor();

        // Try as numeric rate
        bool isNumeric = false;
        double rateVal = 0.0;
        try {
            std::size_t pos = 0;
            rateVal = std::stod(cleanRate, &pos);
            if (pos == cleanRate.size()) isNumeric = true;
        } catch (...) {}

        if (isNumeric) {
            double combined = statFactor * rateVal;
            m << combined;
        } else {
            // Parameter reference - find index
            std::string rateRef = convertRateToMatlab(cleanRate, paramNames);
            if (std::abs(statFactor - 1.0) > 1e-12) {
                m << statFactor << "*" << rateRef;
            } else {
                m << rateRef;
            }
        }

        // Multiply by reactant concentrations
        for (const auto idx : rxn.getReactants()) {
            m << "*species(" << (idx + 1) << ")";
        }

        m << ";\n";
    }
    m << "end\n\n";

    // ===== Nested function: calc_species_deriv =====
    m << "%% Species derivative function\n";
    m << "function Dspecies = calc_species_deriv(t, species, parameters)\n";
    m << "    expressions = calc_expressions(parameters);\n";
    m << "    observables = calc_observables(species, parameters);\n";
    m << "    ratelaws = calc_ratelaws(species, expressions, observables);\n\n";
    m << "    Dspecies = zeros(" << nSpecies << ", 1);\n\n";

    // Use stoichiometry to build derivatives
    for (const auto& entry : stoich) {
        if (fixedSpecies[entry.speciesIndex]) {
            m << "    Dspecies(" << (entry.speciesIndex + 1) << ") = 0; % fixed species\n";
        } else if (entry.rxnCoeffs.empty()) {
            // No reactions affect this species - derivative is 0
            continue;
        } else {
            m << "    Dspecies(" << (entry.speciesIndex + 1) << ") = ";
            bool first = true;
            for (const auto& [rxnIdx, coeff] : entry.rxnCoeffs) {
                if (first) {
                    if (coeff == 1) {
                        m << "ratelaws(" << (rxnIdx + 1) << ")";
                    } else if (coeff == -1) {
                        m << "-ratelaws(" << (rxnIdx + 1) << ")";
                    } else {
                        m << coeff << "*ratelaws(" << (rxnIdx + 1) << ")";
                    }
                } else {
                    if (coeff == 1) {
                        m << " + ratelaws(" << (rxnIdx + 1) << ")";
                    } else if (coeff == -1) {
                        m << " - ratelaws(" << (rxnIdx + 1) << ")";
                    } else if (coeff > 0) {
                        m << " + " << coeff << "*ratelaws(" << (rxnIdx + 1) << ")";
                    } else {
                        m << " - " << (-coeff) << "*ratelaws(" << (rxnIdx + 1) << ")";
                    }
                }
                first = false;
            }
            m << ";\n";
        }
    }

    m << "end\n\n";

    m << "end % main function\n";

    return m.str();
}

std::string MatlabWriter::convertRateToMatlab(const std::string& rate, const std::vector<std::string>& paramNames) {
    std::string result = rate;

    // Replace parameter names with expressions(i) - longer names first to avoid partial matches
    std::vector<std::pair<std::size_t, std::string>> sorted;
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        sorted.push_back({i, paramNames[i]});
    }
    // Sort by name length descending to prevent partial matches
    std::sort(sorted.begin(), sorted.end(), [](const auto& a, const auto& b) {
        return a.second.size() > b.second.size();
    });

    for (const auto& [idx, name] : sorted) {
        std::string paramRef = "expressions(" + std::to_string(idx + 1) + ")";
        std::size_t pos = 0;
        while ((pos = result.find(name, pos)) != std::string::npos) {
            bool validStart = (pos == 0 || !std::isalnum(static_cast<unsigned char>(result[pos - 1])) && result[pos - 1] != '_');
            bool validEnd = (pos + name.length() >= result.length() ||
                           (!std::isalnum(static_cast<unsigned char>(result[pos + name.length()])) && result[pos + name.length()] != '_'));
            if (validStart && validEnd) {
                result.replace(pos, name.length(), paramRef);
                pos += paramRef.length();
            } else {
                pos += name.length();
            }
        }
    }

    return result;
}

std::vector<MatlabWriter::ObservableGroup> MatlabWriter::computeObservableGroups(
    const ast::Model& model, const engine::GeneratedNetwork& network) {
    std::vector<ObservableGroup> groups;
    auto& mutableModel = const_cast<ast::Model&>(model);

    for (const auto& observable : model.getObservables()) {
        ObservableGroup group;
        group.name = observable.getName();
        group.type = observable.getType();

        for (std::size_t speciesIndex = 0; speciesIndex < network.species.size(); ++speciesIndex) {
            std::size_t weight = 0;

            for (const auto& patternText : observable.getPatterns()) {
                try {
                    antlr4::ANTLRInputStream input(patternText);
                    BNGLexer lexer(&input);
                    antlr4::CommonTokenStream tokens(&lexer);
                    BNGParser parser(&tokens);
                    auto* species = parser.species_def();

                    if (parser.getNumberOfSyntaxErrors() == 0) {
                        const auto pattern = bng::parser::buildPatternGraph(species, mutableModel);
                        BNGcore::UllmannSGIso matcher(pattern,
                            network.species.get(speciesIndex).getSpeciesGraph().getGraph());
                        BNGcore::List<BNGcore::Map> maps;
                        weight += matcher.find_maps(maps);
                    }
                } catch (...) {}
            }

            if (observable.getType() == "Species" && weight > 0) {
                weight = 1;
            }

            if (weight > 0) {
                group.entries.push_back({speciesIndex, weight});
            }
        }

        groups.push_back(std::move(group));
    }

    return groups;
}

std::vector<MatlabWriter::StoichEntry> MatlabWriter::computeStoichiometry(
    const engine::GeneratedNetwork& network, std::size_t nSpecies) {
    // Build stoichiometry map: species -> list of (rxn, coeff)
    std::map<std::size_t, std::map<std::size_t, int>> stoichMap;

    for (std::size_t r = 0; r < network.reactions.size(); ++r) {
        const auto& rxn = network.reactions.all()[r];
        for (const auto idx : rxn.getReactants()) {
            stoichMap[idx][r] -= 1;
        }
        for (const auto idx : rxn.getProducts()) {
            stoichMap[idx][r] += 1;
        }
    }

    std::vector<StoichEntry> result;
    for (auto& [specIdx, rxnMap] : stoichMap) {
        StoichEntry entry;
        entry.speciesIndex = specIdx;
        for (auto& [rxnIdx, coeff] : rxnMap) {
            if (coeff != 0) {
                entry.rxnCoeffs.push_back({rxnIdx, coeff});
            }
        }
        if (!entry.rxnCoeffs.empty()) {
            result.push_back(std::move(entry));
        }
    }

    return result;
}

} // namespace bng::io
