#include "MatlabWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>

namespace bng::io {

std::string MatlabWriter::makeMatlabFunctionName(const std::string& modelName) {
    std::string name = modelName;
    // Replace non-alphanumeric with underscore
    std::transform(name.begin(), name.end(), name.begin(), [](char c) {
        return std::isalnum(c) ? c : '_';
    });
    // Ensure starts with letter
    if (!name.empty() && std::isdigit(name[0])) {
        name = "model_" + name;
    }
    return name.empty() ? "bng_model" : name;
}

std::string MatlabWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    Options opts;
    return write(model, network, opts);
}

std::string MatlabWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network, const Options& opts) {
    std::ostringstream m;

    std::string funcName = makeMatlabFunctionName(model.getModelName());

    // Function header
    m << "function [tout, yout, observables] = " << funcName << "()\n";
    m << "% " << funcName << ".m - MATLAB ODE simulation\n";
    m << "% Generated by BioNetGen C++\n\n";

    // Parameters
    m << "%% Parameters\n";
    std::vector<std::string> paramNames;
    for (const auto& param : model.getParameters().all()) {
        paramNames.push_back(param.getName());
    }

    m << "params = [\n";
    for (const auto& param : model.getParameters().all()) {
        m << "    " << param.getValue() << "; % " << param.getName() << "\n";
    }
    m << "];\n\n";

    // Initial conditions
    m << "%% Initial Conditions\n";
    m << "y0 = [\n";
    for (std::size_t i = 0; i < network.species.size(); ++i) {
        const auto& sp = network.species.get(i);
        m << "    " << sp.getAmount() << "; % " << (i + 1) << ": " << sp.getSpeciesGraph().toString() << "\n";
    }
    m << "];\n\n";

    // ODE options
    m << "%% ODE Solver Options\n";
    m << "opts = odeset(\n";
    m << "    'RelTol', " << opts.rtol << ",\n";
    m << "    'AbsTol', " << opts.atol << ",\n";
    m << "    'Stats', '" << (opts.stats ? "on" : "off") << "',\n";
    m << "    'BDF', '" << (opts.bdf ? "on" : "off") << "',\n";
    m << "    'MaxOrder', " << opts.maxOrder << "\n";
    m << ");\n\n";

    // Time span
    m << "%% Time Span\n";
    m << "tspan = linspace(" << opts.tStart << ", " << opts.tEnd << ", " << opts.nSteps << ");\n\n";

    // Solve ODE
    m << "%% Solve ODE\n";
    m << "[tout, yout] = ode15s(@odefun, tspan, y0, opts, params);\n\n";

    // Compute observables
    m << "%% Compute Observables\n";
    m << "observables = zeros(length(tout), " << model.getObservables().size() << ");\n";
    m << "for i = 1:length(tout)\n";
    m << "    observables(i, :) = calcObservables(yout(i, :)');\n";
    m << "end\n\n";

    // Plot
    m << "%% Plot Results\n";
    m << "figure;\n";
    m << "plot(tout, observables);\n";
    m << "legend(";
    for (std::size_t i = 0; i < model.getObservables().size(); ++i) {
        if (i > 0) m << ", ";
        m << "'" << model.getObservables()[i].getName() << "'";
    }
    m << ");\n";
    m << "xlabel('Time');\n";
    m << "ylabel('Observables');\n";
    m << "title('" << model.getModelName() << " Simulation');\n\n";

    // ODE function
    m << "%% ODE Function\n";
    m << "function dydt = odefun(t, y, params)\n";
    m << "    dydt = zeros(" << network.species.size() << ", 1);\n\n";

    // Generate reaction rate equations
    for (const auto& rxn : network.reactions.all()) {
        m << "    % Reaction\n";
        m << "    rate = " << convertRateToMatlab(rxn.getRateLaw(), paramNames);

        // Multiply by reactant concentrations
        for (const auto idx : rxn.getReactants()) {
            m << " * y(" << (idx + 1) << ")";
        }
        m << ";\n";

        // Update derivatives
        for (const auto idx : rxn.getReactants()) {
            m << "    dydt(" << (idx + 1) << ") = dydt(" << (idx + 1) << ") - rate;\n";
        }
        for (const auto idx : rxn.getProducts()) {
            m << "    dydt(" << (idx + 1) << ") = dydt(" << (idx + 1) << ") + rate;\n";
        }
        m << "\n";
    }

    m << "end\n\n";

    // Observable function
    m << "%% Observable Calculation\n";
    m << "function obs = calcObservables(y)\n";
    m << "    obs = zeros(" << model.getObservables().size() << ", 1);\n";

    // Placeholder for observable calculation
    for (std::size_t i = 0; i < model.getObservables().size(); ++i) {
        m << "    obs(" << (i + 1) << ") = 0; % " << model.getObservables()[i].getName() << "\n";
    }

    m << "end\n\n";
    m << "end % main function\n";

    return m.str();
}

std::string MatlabWriter::convertRateToMatlab(const std::string& rate, const std::vector<std::string>& paramNames) {
    std::string result = rate;

    // Replace parameter names with params(i)
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        const auto& name = paramNames[i];
        // Simple replacement (would need proper tokenization for robustness)
        std::string paramRef = "params(" + std::to_string(i + 1) + ")";
        std::size_t pos = 0;
        while ((pos = result.find(name, pos)) != std::string::npos) {
            // Check if this is a whole word
            bool validStart = (pos == 0 || !std::isalnum(result[pos - 1]));
            bool validEnd = (pos + name.length() >= result.length() || !std::isalnum(result[pos + name.length()]));
            if (validStart && validEnd) {
                result.replace(pos, name.length(), paramRef);
                pos += paramRef.length();
            } else {
                pos += name.length();
            }
        }
    }

    return result;
}

} // namespace bng::io
