#include "MdlWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <map>
#include <set>

namespace bng::io {

std::string MdlWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    std::ostringstream out;

    const std::string modelName = model.getModelName();
    const std::size_t nSpecies = network.species.size();
    const std::size_t nRxns = network.reactions.size();

    // Collect unique species names (sanitized for MDL identifiers)
    // MDL identifiers: alphanumeric and underscores
    auto sanitize = [](const std::string& name) -> std::string {
        std::string result;
        result.reserve(name.size());
        for (char c : name) {
            if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
                result += c;
            } else {
                result += '_';
            }
        }
        if (!result.empty() && std::isdigit(static_cast<unsigned char>(result[0]))) {
            result = "S_" + result;
        }
        return result.empty() ? "S_unknown" : result;
    };

    // Build species name map
    std::vector<std::string> speciesNames(nSpecies);
    for (std::size_t i = 0; i < nSpecies; ++i) {
        speciesNames[i] = sanitize(network.species.get(i).getSpeciesGraph().toString());
    }

    // Header comment
    out << "/* MCell MDL file generated by BioNetGen C++ */\n";
    out << "/* Model: " << modelName << " */\n";
    out << "/* Note: Geometry and spatial parameters must be customized by the user. */\n\n";

    // Time step and iterations (defaults)
    out << "ITERATIONS = 1000\n";
    out << "TIME_STEP = 1e-6\n";
    out << "VACANCY_SEARCH_DISTANCE = 10\n\n";

    // === DEFINE_MOLECULES ===
    out << "DEFINE_MOLECULES\n";
    out << "{\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        out << "  " << speciesNames[i] << " { DIFFUSION_CONSTANT_3D = 1e-6 }\n";
    }
    out << "}\n\n";

    // === DEFINE_REACTIONS ===
    out << "DEFINE_REACTIONS\n";
    out << "{\n";
    for (std::size_t r = 0; r < nRxns; ++r) {
        const auto& rxn = network.reactions.all()[r];
        out << "  ";

        // Reactants
        const auto& reactants = rxn.getReactants();
        if (reactants.empty()) {
            out << "NULL";
        } else {
            for (std::size_t i = 0; i < reactants.size(); ++i) {
                if (i > 0) out << " + ";
                out << speciesNames[reactants[i]];
            }
        }

        out << " -> ";

        // Products
        const auto& products = rxn.getProducts();
        if (products.empty()) {
            out << "NULL";
        } else {
            for (std::size_t i = 0; i < products.size(); ++i) {
                if (i > 0) out << " + ";
                out << speciesNames[products[i]];
            }
        }

        // Rate
        const std::string& rateLaw = rxn.getRateLaw();
        std::string cleanRate = rateLaw;
        auto localPos = cleanRate.find("|local:");
        if (localPos != std::string::npos) {
            cleanRate = cleanRate.substr(0, localPos);
        }

        double statFactor = rxn.getFactor();
        bool isNumeric = false;
        double rateVal = 0.0;
        try {
            std::size_t pos = 0;
            rateVal = std::stod(cleanRate, &pos);
            if (pos == cleanRate.size()) isNumeric = true;
        } catch (...) {}

        if (isNumeric) {
            double combined = statFactor * rateVal;
            out << " [" << combined << "]";
        } else {
            if (std::abs(statFactor - 1.0) > 1e-12) {
                out << " [" << statFactor << "*" << cleanRate << "]";
            } else {
                out << " [" << cleanRate << "]";
            }
        }

        out << "\n";
    }
    out << "}\n\n";

    // === Box geometry ===
    out << "/* Default box geometry - customize as needed */\n";
    out << "box BOX\n";
    out << "{\n";
    out << "  CORNERS = [-0.5, -0.5, -0.5], [0.5, 0.5, 0.5]\n";
    out << "}\n\n";

    // === INSTANTIATE ===
    out << "INSTANTIATE World OBJECT\n";
    out << "{\n";
    out << "  box OBJECT box {}\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        double amount = network.species.get(i).getAmount();
        if (amount > 0) {
            int count = static_cast<int>(std::round(amount));
            out << "  " << speciesNames[i] << "_release RELEASE_SITE\n";
            out << "  {\n";
            out << "    SHAPE = World.box\n";
            out << "    MOLECULE = " << speciesNames[i] << "\n";
            out << "    NUMBER_TO_RELEASE = " << count << "\n";
            out << "  }\n";
        }
    }
    out << "}\n";

    return out.str();
}

} // namespace bng::io
