#include "PythonExportWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <map>
#include <set>

#include <antlr4-runtime.h>
#include "generated/BNGLexer.h"
#include "generated/BNGParser.h"
#include "parser/PatternGraphBuilder.hpp"
#include "core/Ullmann.hpp"

namespace bng::io {

std::string PythonExportWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    Options opts;
    return write(model, network, opts);
}

std::string PythonExportWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network, const Options& opts) {
    std::ostringstream py;

    const std::string modelName = model.getModelName();
    const std::size_t nSpecies = network.species.size();
    const std::size_t nRxns = network.reactions.size();

    // Compute observable groups and stoichiometry
    auto groups = computeObservableGroups(model, network);
    auto stoich = computeStoichiometry(network, nSpecies);

    // Collect parameter info
    std::vector<std::string> paramNames;
    std::vector<double> paramValues;
    for (const auto& param : model.getParameters().all()) {
        paramNames.push_back(param.getName());
        paramValues.push_back(param.getValue());
    }
    const std::size_t nParams = paramNames.size();

    // Detect fixed species
    std::vector<bool> fixedSpecies(nSpecies, false);
    for (std::size_t i = 0; i < nSpecies; ++i) {
        fixedSpecies[i] = network.species.get(i).isConstant();
    }

    // ===== Header =====
    py << "# " << modelName << "_pyode.py\n";
    py << "#\n";
    py << "# Python ODE simulation of BioNetGen model '" << modelName << "'.\n";
    py << "# Generated by BioNetGen C++\n";
    py << "#\n";
    py << "# Requires: numpy, scipy\n";
    py << "#   pip install numpy scipy\n";
    py << "#\n";
    py << "# Usage:\n";
    py << "#   python " << modelName << "_pyode.py\n";
    py << "#\n\n";

    // ===== Imports =====
    py << "import numpy as np\n";
    py << "from scipy.integrate import odeint\n";
    py << "import sys\n";
    py << "import os\n\n";

    // ===== Parameters =====
    py << "# Model dimensions\n";
    py << "N_SPECIES = " << nSpecies << "\n";
    py << "N_OBSERVABLES = " << groups.size() << "\n";
    py << "N_REACTIONS = " << nRxns << "\n";
    py << "N_PARAMETERS = " << nParams << "\n\n";

    py << "# Parameter names\n";
    py << "param_names = [\n";
    for (std::size_t i = 0; i < nParams; ++i) {
        py << "    '" << paramNames[i] << "',\n";
    }
    py << "]\n\n";

    py << "# Default parameters\n";
    py << "default_parameters = np.array([\n";
    for (std::size_t i = 0; i < nParams; ++i) {
        py << "    " << std::setprecision(15) << paramValues[i] << ",";
        py << "  # " << paramNames[i] << "\n";
    }
    py << "])\n\n";

    // ===== Species names and initial conditions =====
    py << "# Species names\n";
    py << "species_names = [\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        const auto& sp = network.species.get(i);
        // Escape single quotes in species names
        std::string spName = sp.getSpeciesGraph().toString();
        std::string escaped;
        for (char c : spName) {
            if (c == '\'') escaped += "\\'";
            else escaped += c;
        }
        py << "    '" << escaped << "',\n";
    }
    py << "]\n\n";

    py << "# Default initial species concentrations\n";
    py << "default_y0 = np.array([\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        const auto& sp = network.species.get(i);
        py << "    " << sp.getAmount() << ",";
        py << "  # " << sp.getSpeciesGraph().toString() << "\n";
    }
    py << "])\n\n";

    // ===== Observable names =====
    py << "# Observable names\n";
    py << "observable_names = [\n";
    for (std::size_t g = 0; g < groups.size(); ++g) {
        py << "    '" << groups[g].name << "',\n";
    }
    py << "]\n\n";

    // ===== calc_expressions =====
    py << "def calc_expressions(parameters):\n";
    py << "    \"\"\"Calculate expressions from parameters.\"\"\"\n";
    py << "    expressions = np.zeros(" << nParams << ")\n";
    for (std::size_t i = 0; i < nParams; ++i) {
        py << "    expressions[" << i << "] = parameters[" << i << "]";
        py << "  # " << paramNames[i] << "\n";
    }
    py << "    return expressions\n\n";

    // ===== calc_observables =====
    py << "def calc_observables(species, expressions):\n";
    py << "    \"\"\"Calculate observables from species concentrations.\"\"\"\n";
    py << "    observables = np.zeros(" << groups.size() << ")\n";
    for (std::size_t g = 0; g < groups.size(); ++g) {
        if (groups[g].entries.empty()) {
            py << "    observables[" << g << "] = 0";
        } else {
            py << "    observables[" << g << "] = ";
            bool first = true;
            for (const auto& [specIdx, weight] : groups[g].entries) {
                if (!first) py << " + ";
                if (weight > 1) {
                    py << weight << "*";
                }
                py << "species[" << specIdx << "]";
                first = false;
            }
        }
        py << "  # " << groups[g].name << "\n";
    }
    py << "    return observables\n\n";

    // ===== calc_ratelaws =====
    py << "def calc_ratelaws(species, expressions, observables):\n";
    py << "    \"\"\"Calculate rate laws.\"\"\"\n";
    py << "    ratelaws = np.zeros(" << nRxns << ")\n";
    for (std::size_t r = 0; r < nRxns; ++r) {
        const auto& rxn = network.reactions.all()[r];
        py << "    ratelaws[" << r << "] = ";

        const std::string& rateLaw = rxn.getRateLaw();
        std::string cleanRate = rateLaw;
        auto localPos = cleanRate.find("|local:");
        if (localPos != std::string::npos) {
            cleanRate = cleanRate.substr(0, localPos);
        }

        double statFactor = rxn.getFactor();

        bool isNumeric = false;
        double rateVal = 0.0;
        try {
            std::size_t pos = 0;
            rateVal = std::stod(cleanRate, &pos);
            if (pos == cleanRate.size()) isNumeric = true;
        } catch (...) {}

        if (isNumeric) {
            double combined = statFactor * rateVal;
            py << combined;
        } else {
            std::string rateRef = convertRateToPython(cleanRate, paramNames);
            if (std::abs(statFactor - 1.0) > 1e-12) {
                py << statFactor << "*" << rateRef;
            } else {
                py << rateRef;
            }
        }

        // Multiply by reactant concentrations
        for (const auto idx : rxn.getReactants()) {
            py << "*species[" << idx << "]";
        }

        py << "\n";
    }
    py << "    return ratelaws\n\n";

    // ===== dydt =====
    py << "def dydt(species, t, parameters):\n";
    py << "    \"\"\"ODE right-hand side: species derivatives.\"\"\"\n";
    py << "    expressions = calc_expressions(parameters)\n";
    py << "    observables = calc_observables(species, expressions)\n";
    py << "    ratelaws = calc_ratelaws(species, expressions, observables)\n";
    py << "\n";
    py << "    Dspecies = np.zeros(" << nSpecies << ")\n";

    for (std::size_t i = 0; i < nSpecies; ++i) {
        py << "    Dspecies[" << i << "] = ";
        if (fixedSpecies[i]) {
            py << "0  # fixed species\n";
            continue;
        }

        bool found = false;
        for (const auto& entry : stoich) {
            if (entry.speciesIndex == i) {
                found = true;
                bool first = true;
                for (const auto& [rxnIdx, coeff] : entry.rxnCoeffs) {
                    if (first) {
                        if (coeff == 1) {
                            py << "ratelaws[" << rxnIdx << "]";
                        } else if (coeff == -1) {
                            py << "-ratelaws[" << rxnIdx << "]";
                        } else {
                            py << coeff << "*ratelaws[" << rxnIdx << "]";
                        }
                    } else {
                        if (coeff == 1) {
                            py << " + ratelaws[" << rxnIdx << "]";
                        } else if (coeff == -1) {
                            py << " - ratelaws[" << rxnIdx << "]";
                        } else if (coeff > 0) {
                            py << " + " << coeff << "*ratelaws[" << rxnIdx << "]";
                        } else {
                            py << " - " << (-coeff) << "*ratelaws[" << rxnIdx << "]";
                        }
                    }
                    first = false;
                }
                break;
            }
        }
        if (!found) {
            py << "0";
        }
        py << "\n";
    }

    py << "\n";
    py << "    return Dspecies\n\n";

    // ===== Main simulation =====
    py << "def simulate(timepoints=None, species_init=None, parameters=None):\n";
    py << "    \"\"\"Run ODE simulation and return (timepoints, species_out, observables_out).\"\"\"\n";
    py << "    if timepoints is None:\n";
    py << "        timepoints = np.linspace(" << opts.tStart << ", " << opts.tEnd << ", " << (opts.nSteps + 1) << ")\n";
    py << "    if species_init is None:\n";
    py << "        species_init = default_y0.copy()\n";
    py << "    if parameters is None:\n";
    py << "        parameters = default_parameters.copy()\n";
    py << "\n";
    py << "    # Integrate ODEs\n";
    py << "    species_out = odeint(dydt, species_init, timepoints, args=(parameters,),\n";
    py << "                        atol=" << std::scientific << opts.atol << ", rtol=" << opts.rtol << ")\n";
    py << std::defaultfloat;
    py << "\n";
    py << "    # Calculate observables at each timepoint\n";
    py << "    expressions = calc_expressions(parameters)\n";
    py << "    observables_out = np.zeros((len(timepoints), N_OBSERVABLES))\n";
    py << "    for i in range(len(timepoints)):\n";
    py << "        observables_out[i, :] = calc_observables(species_out[i, :], expressions)\n";
    py << "\n";
    py << "    return timepoints, species_out, observables_out\n\n";

    // ===== Main block =====
    py << "if __name__ == '__main__':\n";
    py << "    # Parse optional command-line arguments: t_end n_steps\n";
    py << "    t_end = " << opts.tEnd << "\n";
    py << "    n_steps = " << opts.nSteps << "\n";
    py << "    if len(sys.argv) > 1:\n";
    py << "        t_end = float(sys.argv[1])\n";
    py << "    if len(sys.argv) > 2:\n";
    py << "        n_steps = int(sys.argv[2])\n";
    py << "\n";
    py << "    timepoints = np.linspace(" << opts.tStart << ", t_end, n_steps + 1)\n";
    py << "    timepoints_sim, species_out, observables_out = simulate(timepoints)\n";
    py << "\n";
    py << "    # Write .cdat file (time + species concentrations)\n";
    py << "    model_name = '" << modelName << "'\n";
    py << "    cdat_path = model_name + '.cdat'\n";
    py << "    with open(cdat_path, 'w') as f:\n";
    py << "        # Header\n";
    py << "        header = '{:<18s}'.format('#') + '  '.join('{:<18s}'.format('time') if i == 0 else '{:<18s}'.format(species_names[i-1]) for i in range(N_SPECIES + 1))\n";
    py << "        # Actually write: first column is time\n";
    py << "        for i in range(len(timepoints_sim)):\n";
    py << "            line = '{:<18.12e}'.format(timepoints_sim[i])\n";
    py << "            for j in range(N_SPECIES):\n";
    py << "                line += '  {:<18.12e}'.format(species_out[i, j])\n";
    py << "            f.write(line + '\\n')\n";
    py << "    print(f'Wrote species output to {cdat_path}')\n";
    py << "\n";
    py << "    # Write .gdat file (time + observables)\n";
    py << "    gdat_path = model_name + '.gdat'\n";
    py << "    with open(gdat_path, 'w') as f:\n";
    py << "        # Header\n";
    py << "        header = '{:<18s}'.format('#          time')\n";
    py << "        for name in observable_names:\n";
    py << "            header += '  {:<18s}'.format(name)\n";
    py << "        f.write(header + '\\n')\n";
    py << "        for i in range(len(timepoints_sim)):\n";
    py << "            line = '{:<18.12e}'.format(timepoints_sim[i])\n";
    py << "            for j in range(N_OBSERVABLES):\n";
    py << "                line += '  {:<18.12e}'.format(observables_out[i, j])\n";
    py << "            f.write(line + '\\n')\n";
    py << "    print(f'Wrote observables output to {gdat_path}')\n";

    return py.str();
}

std::string PythonExportWriter::convertRateToPython(const std::string& rate, const std::vector<std::string>& paramNames) {
    std::string result = rate;

    // Replace parameter names with expressions[i] - longer names first
    std::vector<std::pair<std::size_t, std::string>> sorted;
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        sorted.push_back({i, paramNames[i]});
    }
    std::sort(sorted.begin(), sorted.end(), [](const auto& a, const auto& b) {
        return a.second.size() > b.second.size();
    });

    for (const auto& [idx, name] : sorted) {
        std::string paramRef = "expressions[" + std::to_string(idx) + "]";
        std::size_t pos = 0;
        while ((pos = result.find(name, pos)) != std::string::npos) {
            bool validStart = (pos == 0 || (!std::isalnum(static_cast<unsigned char>(result[pos - 1])) && result[pos - 1] != '_'));
            bool validEnd = (pos + name.length() >= result.length() ||
                           (!std::isalnum(static_cast<unsigned char>(result[pos + name.length()])) && result[pos + name.length()] != '_'));
            if (validStart && validEnd) {
                result.replace(pos, name.length(), paramRef);
                pos += paramRef.length();
            } else {
                pos += name.length();
            }
        }
    }

    // Replace ^ with ** for Python exponentiation
    std::size_t pos = 0;
    while ((pos = result.find('^', pos)) != std::string::npos) {
        result.replace(pos, 1, "**");
        pos += 2;
    }

    return result;
}

std::vector<PythonExportWriter::ObservableGroup> PythonExportWriter::computeObservableGroups(
    const ast::Model& model, const engine::GeneratedNetwork& network) {
    std::vector<ObservableGroup> groups;
    auto& mutableModel = const_cast<ast::Model&>(model);

    for (const auto& observable : model.getObservables()) {
        ObservableGroup group;
        group.name = observable.getName();
        group.type = observable.getType();

        for (std::size_t speciesIndex = 0; speciesIndex < network.species.size(); ++speciesIndex) {
            std::size_t weight = 0;

            for (const auto& patternText : observable.getPatterns()) {
                try {
                    antlr4::ANTLRInputStream input(patternText);
                    BNGLexer lexer(&input);
                    antlr4::CommonTokenStream tokens(&lexer);
                    BNGParser parser(&tokens);
                    auto* species = parser.species_def();

                    if (parser.getNumberOfSyntaxErrors() == 0) {
                        const auto pattern = bng::parser::buildPatternGraph(species, mutableModel);
                        BNGcore::UllmannSGIso matcher(pattern,
                            network.species.get(speciesIndex).getSpeciesGraph().getGraph());
                        BNGcore::List<BNGcore::Map> maps;
                        weight += matcher.find_maps(maps);
                    }
                } catch (...) {}
            }

            if (observable.getType() == "Species" && weight > 0) {
                weight = 1;
            }

            if (weight > 0) {
                group.entries.push_back({speciesIndex, weight});
            }
        }

        groups.push_back(std::move(group));
    }

    return groups;
}

std::vector<PythonExportWriter::StoichEntry> PythonExportWriter::computeStoichiometry(
    const engine::GeneratedNetwork& network, std::size_t nSpecies) {
    std::map<std::size_t, std::map<std::size_t, int>> stoichMap;

    for (std::size_t r = 0; r < network.reactions.size(); ++r) {
        const auto& rxn = network.reactions.all()[r];
        for (const auto idx : rxn.getReactants()) {
            stoichMap[idx][r] -= 1;
        }
        for (const auto idx : rxn.getProducts()) {
            stoichMap[idx][r] += 1;
        }
    }

    std::vector<StoichEntry> result;
    for (auto& [specIdx, rxnMap] : stoichMap) {
        StoichEntry entry;
        entry.speciesIndex = specIdx;
        for (auto& [rxnIdx, coeff] : rxnMap) {
            if (coeff != 0) {
                entry.rxnCoeffs.push_back({rxnIdx, coeff});
            }
        }
        if (!entry.rxnCoeffs.empty()) {
            result.push_back(std::move(entry));
        }
    }

    return result;
}

} // namespace bng::io
