#include "SscWriter.hpp"

#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <map>
#include <set>

namespace bng::io {

std::string SscWriter::write(const ast::Model& model, const engine::GeneratedNetwork& network) {
    std::ostringstream out;

    const std::string modelName = model.getModelName();
    const std::size_t nSpecies = network.species.size();
    const std::size_t nRxns = network.reactions.size();

    // Collect parameter info
    std::vector<std::string> paramNames;
    std::vector<double> paramValues;
    for (const auto& param : model.getParameters().all()) {
        paramNames.push_back(param.getName());
        paramValues.push_back(param.getValue());
    }

    // Sanitize species names for SSC identifiers
    auto sanitize = [](const std::string& name) -> std::string {
        std::string result;
        result.reserve(name.size());
        for (char c : name) {
            if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
                result += c;
            } else {
                result += '_';
            }
        }
        if (!result.empty() && std::isdigit(static_cast<unsigned char>(result[0]))) {
            result = "S_" + result;
        }
        return result.empty() ? "S_unknown" : result;
    };

    // Build species name map
    std::vector<std::string> speciesNamesSanitized(nSpecies);
    for (std::size_t i = 0; i < nSpecies; ++i) {
        speciesNamesSanitized[i] = sanitize(network.species.get(i).getSpeciesGraph().toString());
    }

    // Header
    out << "// SSC (Stochastic Simulation Compiler) model file\n";
    out << "// Model: " << modelName << "\n";
    out << "// Generated by BioNetGen C++\n\n";

    // === Parameters ===
    out << "// Parameters\n";
    for (std::size_t i = 0; i < paramNames.size(); ++i) {
        out << "const " << paramNames[i] << " = "
            << std::setprecision(15) << paramValues[i] << ";\n";
    }
    out << "\n";

    // === Species ===
    out << "// Species\n";
    for (std::size_t i = 0; i < nSpecies; ++i) {
        double amount = network.species.get(i).getAmount();
        int count = static_cast<int>(std::round(amount));
        out << "new " << speciesNamesSanitized[i] << "(" << count << ");\n";
    }
    out << "\n";

    // === Reactions ===
    out << "// Reactions\n";
    for (std::size_t r = 0; r < nRxns; ++r) {
        const auto& rxn = network.reactions.all()[r];

        // Reactants
        const auto& reactants = rxn.getReactants();
        if (reactants.empty()) {
            out << "0";
        } else {
            for (std::size_t i = 0; i < reactants.size(); ++i) {
                if (i > 0) out << " + ";
                out << speciesNamesSanitized[reactants[i]];
            }
        }

        out << " -> ";

        // Products
        const auto& products = rxn.getProducts();
        if (products.empty()) {
            out << "0";
        } else {
            for (std::size_t i = 0; i < products.size(); ++i) {
                if (i > 0) out << " + ";
                out << speciesNamesSanitized[products[i]];
            }
        }

        // Rate
        const std::string& rateLaw = rxn.getRateLaw();
        std::string cleanRate = rateLaw;
        auto localPos = cleanRate.find("|local:");
        if (localPos != std::string::npos) {
            cleanRate = cleanRate.substr(0, localPos);
        }

        double statFactor = rxn.getFactor();
        bool isNumeric = false;
        double rateVal = 0.0;
        try {
            std::size_t pos = 0;
            rateVal = std::stod(cleanRate, &pos);
            if (pos == cleanRate.size()) isNumeric = true;
        } catch (...) {}

        out << ", ";
        if (isNumeric) {
            double combined = statFactor * rateVal;
            out << combined;
        } else {
            if (std::abs(statFactor - 1.0) > 1e-12) {
                out << statFactor << "*" << cleanRate;
            } else {
                out << cleanRate;
            }
        }

        out << ";\n";
    }

    return out.str();
}

} // namespace bng::io
